# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Maowu1dnATetSGI3d_qj8Edv9KzpN2bg
"""

"""
One-compartment oral PK with first-order absorption and direct stimulatory sigmoid Emax PD.

Units:
 - time: hours (h)
 - amount: milligrams (mg)
 - volume: liters (L)
 - clearance: L/h
 - concentration: mg/L
 - ka, ke: 1/h
 - F: dimensionless (0..1)
 - effect units: user-defined (E0, Emax)

Deterministic, single-dose base implementation with explicit validation and diagnostics.
"""
from typing import Dict, Optional, Sequence, Tuple
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# -------------------------
# Default numerical options
# -------------------------
DEFAULT_RK_METHOD = "RK45"
DEFAULT_RTOL = 1e-8
DEFAULT_ATOL = 1e-10
# ke consistency tolerances
KE_RTOL = 1e-8
KE_ATOL = 1e-12


# -------------------------
# Validation utilities
# -------------------------
def _is_finite_number(x: float) -> bool:
    return np.isfinite(x)


def validate_parameters(
    Dose: float,
    F: float,
    ka: float,
    V: float,
    CL: float,
    EC50: float,
    gamma: float,
    Emax: float,
    E0: float,
    t_start: float,
    t_end: float,
    t_eval: Optional[Sequence[float]],
    ke_supplied: Optional[float] = None,
) -> Tuple[float, float]:
    """
    Validate inputs and compute ke = CL / V.
    Raises ValueError with informative messages for invalid inputs.
    Returns computed ke and the negativity tolerance (abs).
    """
    # Basic numeric checks
    params = dict(Dose=Dose, F=F, ka=ka, V=V, CL=CL, EC50=EC50, gamma=gamma, Emax=Emax, E0=E0, t_start=t_start, t_end=t_end)
    for name, val in params.items():
        if not _is_finite_number(val):
            raise ValueError(f"Parameter {name} must be a finite number; got {val!r}.")

    if Dose < 0:
        raise ValueError("Dose must be >= 0.")
    if not (0.0 <= F <= 1.0):
        raise ValueError("F (bioavailability) must satisfy 0 <= F <= 1.")
    if ka <= 0.0:
        raise ValueError("ka must be > 0 (1/h).")
    if V <= 0.0:
        raise ValueError("V must be > 0 (L).")
    if CL <= 0.0:
        raise ValueError("CL must be > 0 (L/h).")
    if EC50 <= 0.0:
        raise ValueError("EC50 must be > 0 (mg/L).")
    if gamma <= 0.0:
        raise ValueError("gamma must be > 0 (dimensionless).")
    if Emax < 0.0:
        raise ValueError("Emax must be >= 0 for the stimulatory model.")
    # time checks
    if not (_is_finite_number(t_start) and _is_finite_number(t_end)):
        raise ValueError("t_start and t_end must be finite numbers.")
    if t_end <= t_start:
        raise ValueError("t_end must be greater than t_start.")
    if t_eval is not None:
        t_eval = np.asarray(t_eval, dtype=float)
        if t_eval.ndim != 1:
            raise ValueError("t_eval must be a 1-D sequence of times.")
        if not np.all(np.isfinite(t_eval)):
            raise ValueError("All t_eval values must be finite.")
        if not (t_eval[0] >= t_start - 1e-14 and t_eval[-1] <= t_end + 1e-14):
            raise ValueError("t_eval values must lie within [t_start, t_end].")
        if not np.all(np.diff(t_eval) >= 0):
            raise ValueError("t_eval must be ordered non-decreasing.")
    # compute ke and compare if supplied
    ke = float(CL / V)
    if ke_supplied is not None:
        if not _is_finite_number(ke_supplied):
            raise ValueError("Supplied ke must be finite.")
        if not np.isclose(ke, ke_supplied, rtol=KE_RTOL, atol=KE_ATOL):
            raise ValueError(
                f"Supplied ke={ke_supplied:.12g} is inconsistent with CL/V={ke:.12g} "
                f"(tolerances rtol={KE_RTOL}, atol={KE_ATOL})."
            )
    # negativity tolerance relative to problem scale (amount units: mg)
    neg_tol = max(1e-12, 1e-8 * max(1.0, float(Dose)))
    return ke, neg_tol


# -------------------------
# PK ODE function
# -------------------------
def pk_ode(t: float, y: Sequence[float], ka: float, ke: float, F: float) -> np.ndarray:
    """
    ODE right-hand side for the two-state PK model.
    y[0] = A_gut (mg)
    y[1] = A_central (mg)
    Returns derivatives [dA_gut/dt, dA_central/dt].
    """
    A_gut = float(y[0])
    A_central = float(y[1])
    dA_gut = -ka * A_gut
    dA_central = F * ka * A_gut - ke * A_central
    return np.array([dA_gut, dA_central], dtype=float)


# -------------------------
# PD function: stimulatory sigmoid Emax
# -------------------------
def sigmoid_emax(
    concentration: np.ndarray,
    E0: float,
    Emax: float,
    EC50: float,
    gamma: float,
    conc_neg_tol: float = 0.0,
) -> np.ndarray:
    """
    Compute E(C) = E0 + Emax * C^gamma / (EC50^gamma + C^gamma).
    Works with scalars or arrays (NumPy). Safely handles tiny negative concentrations
    by clipping to zero if abs(value) <= conc_neg_tol; raises if more negative.
    """
    C = np.asarray(concentration, dtype=float)
    # Handle tiny negative concentrations from numerical error
    if conc_neg_tol < 0:
        raise ValueError("conc_neg_tol must be nonnegative.")
    neg_mask = C < 0.0
    if np.any(neg_mask):
        max_neg = float(np.min(C[neg_mask]))
        if max_neg < -conc_neg_tol:
            raise ValueError(
                f"Concentration has values more negative ({max_neg:.3g}) than allowed tolerance {-conc_neg_tol:.3g}."
            )
        # clip tiny negatives to zero for stable fractional powers
        C = np.maximum(C, 0.0)
    # Now compute Hill fraction
    num = np.power(C, gamma)
    denom = np.power(EC50, gamma) + num
    # Avoid division by zero (EC50>0 ensures denom>0)
    frac = np.zeros_like(C, dtype=float)
    # denom > 0 guaranteed because EC50>0
    frac = num / denom
    return float(E0) + float(Emax) * frac


# -------------------------
# Simulation function
# -------------------------
def simulate_pkpd(
    Dose: float,
    F: float,
    ka: float,
    V: float,
    CL: float,
    E0: float,
    Emax: float,
    EC50: float,
    gamma: float,
    t_start: float = 0.0,
    t_end: float = 48.0,
    t_eval: Optional[Sequence[float]] = None,
    ke_supplied: Optional[float] = None,
    method: str = DEFAULT_RK_METHOD,
    rtol: float = DEFAULT_RTOL,
    atol: float = DEFAULT_ATOL,
) -> Dict[str, np.ndarray]:
    """
    Simulate the two-state PK model and PD effect over the given time range.

    Returns a dict with keys:
      "time", "A_gut", "A_central", "concentration", "effect", "ke", "units"
    """
    # Validate inputs and compute derived ke and negativity tolerance
    ke, neg_tol = validate_parameters(
        Dose=Dose,
        F=F,
        ka=ka,
        V=V,
        CL=CL,
        EC50=EC50,
        gamma=gamma,
        Emax=Emax,
        E0=E0,
        t_start=t_start,
        t_end=t_end,
        t_eval=t_eval,
        ke_supplied=ke_supplied,
    )

    # Build evaluation grid if not provided: spacing 0.05 h by default
    if t_eval is None:
        dt = 0.05  # hours
        t_eval = np.arange(t_start, t_end + dt / 2.0, dt, dtype=float)
    else:
        t_eval = np.asarray(t_eval, dtype=float)

    # Max step policy:
    # Choose max_step no larger than the evaluation spacing and no larger than a fraction
    # of the fastest PK timescale. Fastest rate = max(ka, ke); timescale = 1/fastest_rate.
    fastest_rate = max(ka, ke)
    if fastest_rate <= 0.0:
        # degenerate; fall back to evaluation spacing
        max_step_by_rate = np.inf
    else:
        max_step_by_rate = 0.1 / fastest_rate  # 0.1 of the fastest timescale
    eval_spacing = np.min(np.diff(t_eval)) if t_eval.size > 1 else (t_end - t_start)
    max_step = float(min(eval_spacing, max_step_by_rate))

    # initial conditions according to base dosing convention:
    # A_gut(0) = Dose, A_central(0) = 0
    y0 = np.array([float(Dose), 0.0], dtype=float)

    # Integrate ODE
    sol = solve_ivp(
        fun=lambda t, y: pk_ode(t, y, ka=ka, ke=ke, F=F),
        t_span=(float(t_start), float(t_end)),
        y0=y0,
        method=method,
        t_eval=t_eval,
        rtol=rtol,
        atol=atol,
        max_step=max_step,
    )

    # Diagnostics on solver result
    if sol.status != 0 or not sol.success:
        raise RuntimeError(f"ODE solver failed: message='{sol.message}', status={sol.status}")

    # Post-process states
    A_gut = np.asarray(sol.y[0, :], dtype=float)
    A_central = np.asarray(sol.y[1, :], dtype=float)
    time = np.asarray(sol.t, dtype=float)

    # Finite checks
    if not (np.all(np.isfinite(A_gut)) and np.all(np.isfinite(A_central)) and np.all(np.isfinite(time))):
        raise RuntimeError("Integration produced non-finite values in states or time.")

    # Negative-state policy:
    # Clip tiny negative amounts (within neg_tol) for derived outputs, but raise if any state < -neg_tol
    min_A_gut = float(np.min(A_gut))
    min_A_central = float(np.min(A_central))
    if min_A_gut < -neg_tol or min_A_central < -neg_tol:
        raise RuntimeError(
            f"Solver produced materially negative state(s): min(A_gut)={min_A_gut:.3g}, min(A_central)={min_A_central:.3g}; "
            f"negativity tolerance={neg_tol:.3g}."
        )
    # For downstream outputs, clip small negatives to zero
    A_gut_clipped = np.maximum(A_gut, 0.0)
    A_central_clipped = np.maximum(A_central, 0.0)

    # Concentration (mg/L)
    concentration = A_central_clipped / float(V)

    # Concentration nonnegativity check (allow tiny negatives handled above)
    if not np.all(np.isfinite(concentration)):
        raise RuntimeError("Non-finite concentration values encountered.")
    if np.min(concentration) < -1e-14:
        # numerical paranoia; should not occur because we clipped amounts
        raise RuntimeError("Concentration has negative values beyond minimal numerical noise.")

    # Compute effect
    effect = sigmoid_emax(concentration, E0=E0, Emax=Emax, EC50=EC50, gamma=gamma, conc_neg_tol=1e-14)

    # Package results with units metadata
    results = {
        "time": time,  # h
        "A_gut": A_gut_clipped,  # mg
        "A_central": A_central_clipped,  # mg
        "concentration": concentration,  # mg/L
        "effect": effect,  # effect units
        "ke": ke,  # 1/h
        "units": {
            "time": "h",
            "amount": "mg",
            "volume": "L",
            "concentration": "mg/L",
            "ke": "1/h",
            "effect": "user-defined units",
        },
        # metadata for reproducibility
        "meta": {
            "method": method,
            "rtol": rtol,
            "atol": atol,
            "max_step": max_step,
            "negativity_tolerance_amount_mg": neg_tol,
            "ke_consistency_rtol": KE_RTOL,
            "ke_consistency_atol": KE_ATOL,
            "dosing_convention": "A_gut(0)=Dose (single instantaneous oral dose at t=0)",
            "bioavailability_convention": "F applied in absorption flux F*ka*A_gut; CL and V are systemic (not apparent)",
        },
    }
    return results


# -------------------------
# Plotting
# -------------------------
def plot_pkpd(results: Dict[str, np.ndarray], title_suffix: str = "") -> None:
    """
    Plot concentration-time and effect-time from simulation results dictionary.
    Does not re-run simulation; accepts the returned dict from simulate_pkpd.
    """
    t = results["time"]
    C = results["concentration"]
    E = results["effect"]
    units = results.get("units", {})
    time_unit = units.get("time", "h")
    conc_unit = units.get("concentration", "mg/L")
    eff_unit = units.get("effect", "units")

    fig, axes = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
    axes[0].plot(t, C, color="C0", lw=1.5)
    axes[0].set_ylabel(f"Concentration ({conc_unit})", fontsize=10)
    axes[0].set_title(f"Concentration vs Time {title_suffix}".strip())
    axes[0].grid(True)

    axes[1].plot(t, E, color="C1", lw=1.5)
    axes[1].set_xlabel(f"Time ({time_unit})", fontsize=10)
    axes[1].set_ylabel(f"Effect ({eff_unit})", fontsize=10)
    axes[1].set_title(f"Pharmacodynamic Effect vs Time {title_suffix}".strip())
    axes[1].grid(True)

    plt.tight_layout()
    plt.show()


# -------------------------
# Runnable demonstration
# -------------------------
if __name__ == "__main__":
    # Synthetic demonstration parameters (for demonstration only, not a real drug)
    Dose = 100.0  # mg
    F = 0.6  # fraction (dimensionless)
    ka = 1.0  # 1/h (absorption is relatively fast; t1/2,abs ~ 0.693 h)
    V = 20.0  # L
    CL = 1.0  # L/h -> ke = 0.05 1/h (t1/2,elim ~ 13.86 h)
    # PD parameters
    E0 = 0.0  # baseline effect units
    Emax = 100.0  # effect units
    EC50 = 2.0  # mg/L
    gamma = 1.5  # Hill coefficient (dimensionless)

    # Simulation time grid defaults (0..48 h, dt=0.05 h)
    t_start = 0.0
    t_end = 48.0
    dt = 0.05
    t_eval = np.arange(t_start, t_end + dt / 2.0, dt, dtype=float)

    # Run simulation
    results = simulate_pkpd(
        Dose=Dose,
        F=F,
        ka=ka,
        V=V,
        CL=CL,
        E0=E0,
        Emax=Emax,
        EC50=EC50,
        gamma=gamma,
        t_start=t_start,
        t_end=t_end,
        t_eval=t_eval,
    )

    # Validation checks (PK identity, PD behavior, state checks)
    ke_computed = results["ke"]
    # PK consistency check: ke = CL / V
    ke_expected = CL / V
    assert np.isclose(ke_computed, ke_expected, rtol=KE_RTOL, atol=KE_ATOL), "ke inconsistency."

    # PD checks
    C_zero = 0.0
    C_half = EC50
    C_high = 1000.0 * EC50
    tol_pd = 1e-9
    E_at_0 = sigmoid_emax(np.array([C_zero]), E0=E0, Emax=Emax, EC50=EC50, gamma=gamma)[0]
    E_at_half = sigmoid_emax(np.array([C_half]), E0=E0, Emax=Emax, EC50=EC50, gamma=gamma)[0]
    E_at_high = sigmoid_emax(np.array([C_high]), E0=E0, Emax=Emax, EC50=EC50, gamma=gamma)[0]
    assert np.allclose(E_at_0, E0, rtol=1e-12, atol=1e-12), "PD check failed at C=0."
    assert np.allclose(E_at_half, E0 + Emax / 2.0, rtol=1e-8, atol=1e-12), "PD check failed at C=EC50."
    assert np.isclose(E_at_high, E0 + Emax, rtol=1e-6, atol=1e-12), "PD high-concentration limit check failed."

    # State checks
    assert np.all(np.isfinite(results["A_gut"])) and np.all(np.isfinite(results["A_central"])), "Non-finite states."
    assert np.min(results["A_gut"]) >= -results["meta"]["negativity_tolerance_amount_mg"] - 1e-15
    assert np.min(results["A_central"]) >= -results["meta"]["negativity_tolerance_amount_mg"] - 1e-15
    assert np.all(results["concentration"] >= -1e-14)

    # Print concise diagnostics
    print("Simulation completed successfully.")
    print(f"ke (computed) = {ke_computed:.8g} 1/h, ke (CL/V) = {ke_expected:.8g} 1/h")
    print(f"PD checks: E(0)={E_at_0:.6g} (expected {E0}), E(EC50)={E_at_half:.6g} (expected {E0 + Emax/2})")
    print(f"Effect at 1000*EC50 ≈ {E_at_high:.6g} (expected {E0 + Emax})")

    # Plot results
    plot_pkpd(results, title_suffix="(synthetic demonstration)")