# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ffxu2RxDDwnnTFIK5KCcaDgwyS2evOqQ
"""

# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Maowu1dnATetSGI3d_qj8Edv9KzpN2bg
"""

"""
One-compartment oral PK with first-order absorption and direct stimulatory sigmoid Emax PD.
Supports single-dose and repeated-dose oral regimens.

Units:
 - time: hours (h)
 - amount: milligrams (mg)
 - volume: liters (L)
 - clearance: L/h
 - concentration: mg/L
 - ka, ke: 1/h
 - F: dimensionless (0..1)
 - effect units: user-defined (E0, Emax)

Deterministic PK/PD implementation with explicit validation and diagnostics.
"""
from typing import Dict, Optional, Sequence, Tuple, Any
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# -------------------------
# Default numerical options
# -------------------------
DEFAULT_RK_METHOD = "RK45"
DEFAULT_RTOL = 1e-8
DEFAULT_ATOL = 1e-10
# ke consistency tolerances
KE_RTOL = 1e-8
KE_ATOL = 1e-12
# floating-point tolerance for event-time matching
EVENT_TIME_TOL = 1e-10


# -------------------------
# Validation utilities
# -------------------------
def _is_finite_number(x: float) -> bool:
    return np.isfinite(x)


def validate_parameters(
    Dose: float,
    F: float,
    ka: float,
    V: float,
    CL: float,
    EC50: float,
    gamma: float,
    Emax: float,
    E0: float,
    t_start: float,
    t_end: float,
    t_eval: Optional[Sequence[float]],
    ke_supplied: Optional[float] = None,
) -> Tuple[float, float]:
    """
    Validate inputs and compute ke = CL / V.
    Raises ValueError with informative messages for invalid inputs.
    Returns computed ke and the negativity tolerance (abs, in mg).
    """
    # Basic numeric checks
    params = dict(Dose=Dose, F=F, ka=ka, V=V, CL=CL, EC50=EC50, gamma=gamma, Emax=Emax, E0=E0, t_start=t_start, t_end=t_end)
    for name, val in params.items():
        if not _is_finite_number(val):
            raise ValueError(f"Parameter {name} must be a finite number; got {val!r}.")

    if Dose < 0:
        raise ValueError("Dose must be >= 0.")
    if not (0.0 <= F <= 1.0):
        raise ValueError("F (bioavailability) must satisfy 0 <= F <= 1.")
    if ka <= 0.0:
        raise ValueError("ka must be > 0 (1/h).")
    if V <= 0.0:
        raise ValueError("V must be > 0 (L).")
    if CL <= 0.0:
        raise ValueError("CL must be > 0 (L/h).")
    if EC50 <= 0.0:
        raise ValueError("EC50 must be > 0 (mg/L).")
    if gamma <= 0.0:
        raise ValueError("gamma must be > 0 (dimensionless).")
    if Emax < 0.0:
        raise ValueError("Emax must be >= 0 for the stimulatory model.")
    # time checks
    if not (_is_finite_number(t_start) and _is_finite_number(t_end)):
        raise ValueError("t_start and t_end must be finite numbers.")
    if t_end <= t_start:
        raise ValueError("t_end must be greater than t_start.")
    if t_eval is not None:
        t_eval_arr = np.asarray(t_eval, dtype=float)
        if t_eval_arr.ndim != 1:
            raise ValueError("t_eval must be a 1-D sequence of times.")
        if t_eval_arr.size < 1:
            raise ValueError("t_eval must have at least 1 element.")
        if not np.all(np.isfinite(t_eval_arr)):
            raise ValueError("All t_eval values must be finite.")
        if not (t_eval_arr[0] >= t_start - 1e-14 and t_eval_arr[-1] <= t_end + 1e-14):
            raise ValueError("t_eval values must lie within [t_start, t_end].")
        if t_eval_arr.size > 1:
            if not np.all(np.diff(t_eval_arr) > 0):
                raise ValueError("t_eval must be strictly increasing (no duplicates).")
    # compute ke and compare if supplied
    ke = float(CL / V)
    if ke_supplied is not None:
        if not _is_finite_number(ke_supplied):
            raise ValueError("Supplied ke must be finite.")
        if not np.isclose(ke, ke_supplied, rtol=KE_RTOL, atol=KE_ATOL):
            raise ValueError(
                f"Supplied ke={ke_supplied:.12g} is inconsistent with CL/V={ke:.12g} "
                f"(tolerances rtol={KE_RTOL}, atol={KE_ATOL})."
            )
    # negativity tolerance relative to problem scale (amount units: mg)
    neg_tol = max(1e-12, 1e-8 * max(1.0, float(Dose)))
    return ke, neg_tol


def validate_solver_controls(
    rtol: float,
    atol: float,
) -> None:
    """
    Validate that ODE solver tolerances are scalar, finite, and strictly positive.
    Raises ValueError for invalid inputs.
    """
    if not _is_finite_number(rtol):
        raise ValueError(f"rtol must be finite; got {rtol!r}.")
    if not _is_finite_number(atol):
        raise ValueError(f"atol must be finite; got {atol!r}.")
    if rtol <= 0.0:
        raise ValueError(f"rtol must be > 0; got {rtol}.")
    if atol <= 0.0:
        raise ValueError(f"atol must be > 0; got {atol}.")


def build_or_validate_dosing_schedule(
    Dose: float,
    tau: Optional[float],
    n_doses: Optional[int],
    dose_times: Optional[Sequence[float]],
    dose_amounts: Optional[Sequence[float]],
    t_start: float,
    t_end: float,
) -> Tuple[np.ndarray, np.ndarray, int]:
    """
    Normalize and validate dosing specification into canonical dose_times and dose_amounts arrays.

    Rules:
      Case 1 (legacy/default): No tau, n_doses, dose_times, dose_amounts supplied.
               One dose = Dose at t_start.
      Case 2 (regular): tau and n_doses supplied. dose_times constructed as t_start + i*tau.
      Case 3 (explicit): dose_times supplied. dose_amounts either supplied or defaulted to Dose.

    Returns
    -------
    dose_times : ndarray (1-D, float)
        Strictly increasing dose times.
    dose_amounts : ndarray (1-D, float)
        Corresponding dose amounts.
    n_doses : int
        Number of doses.

    Raises
    ------
    ValueError
        For invalid, incomplete, or conflicting specifications.
    """

    # Determine which case (legacy, regular, explicit)
    has_tau = tau is not None
    has_n_doses = n_doses is not None
    has_dose_times = dose_times is not None
    has_dose_amounts = dose_amounts is not None

    # Validate mutual exclusivity
    if has_dose_amounts and not has_dose_times:
        raise ValueError("dose_amounts supplied without dose_times.")

    if has_tau and not has_n_doses:
        raise ValueError("tau supplied without n_doses.")
    if has_n_doses and not has_tau:
        raise ValueError("n_doses supplied without tau.")

    if has_tau and has_dose_times:
        raise ValueError("Cannot specify both regular regimen (tau, n_doses) and explicit dose_times.")
    if has_tau and has_dose_amounts:
        raise ValueError("Cannot specify both regular regimen (tau, n_doses) and explicit dose_amounts.")

    # Case 1: Legacy/default
    if not has_tau and not has_dose_times:
        dose_times_arr = np.array([t_start], dtype=float)
        dose_amounts_arr = np.array([Dose], dtype=float)
        return dose_times_arr, dose_amounts_arr, 1

    # Case 2: Regular repeated regimen
    if has_tau and has_n_doses:
        # Validate tau and n_doses
        if not _is_finite_number(tau):
            raise ValueError(f"tau must be finite; got {tau!r}.")
        if tau <= 0.0:
            raise ValueError(f"tau must be > 0; got {tau}.")
        if not isinstance(n_doses, (int, np.integer)):
            raise ValueError(f"n_doses must be an integer; got {type(n_doses).__name__}.")
        if n_doses <= 0:
            raise ValueError(f"n_doses must be >= 1; got {n_doses}.")

        # Construct dose times
        dose_times_arr = np.array([t_start + i * tau for i in range(int(n_doses))], dtype=float)
        dose_amounts_arr = np.full(int(n_doses), float(Dose), dtype=float)

        # Validate that all doses lie in [t_start, t_end]
        if not np.all((dose_times_arr >= t_start - 1e-14) & (dose_times_arr <= t_end + 1e-14)):
            raise ValueError(
                f"Regular regimen with tau={tau}, n_doses={n_doses} produces dose times outside [t_start={t_start}, t_end={t_end}]. "
                f"Latest dose at t={dose_times_arr[-1]:.6g}."
            )

        return dose_times_arr, dose_amounts_arr, int(n_doses)

    # Case 3: Explicit schedule
    if has_dose_times:
        dose_times_arr = np.asarray(dose_times, dtype=float)
        if dose_times_arr.ndim != 1:
            raise ValueError("dose_times must be a 1-D sequence.")
        if dose_times_arr.size < 1:
            raise ValueError("dose_times must have at least 1 element.")
        if not np.all(np.isfinite(dose_times_arr)):
            raise ValueError("All dose_times values must be finite.")
        if dose_times_arr.size > 1:
            if not np.all(np.diff(dose_times_arr) > 0):
                raise ValueError("dose_times must be strictly increasing (no duplicates).")

        # Check all times in [t_start, t_end]
        if not np.all((dose_times_arr >= t_start - 1e-14) & (dose_times_arr <= t_end + 1e-14)):
            bad_idx = np.where((dose_times_arr < t_start - 1e-14) | (dose_times_arr > t_end + 1e-14))[0]
            bad_time = dose_times_arr[bad_idx[0]]
            raise ValueError(
                f"dose_times contains value {bad_time:.6g} outside [t_start={t_start}, t_end={t_end}]."
            )

        # Determine dose_amounts
        if has_dose_amounts:
            dose_amounts_arr = np.asarray(dose_amounts, dtype=float)
            if dose_amounts_arr.ndim != 1:
                raise ValueError("dose_amounts must be a 1-D sequence.")
            if dose_amounts_arr.size != dose_times_arr.size:
                raise ValueError(
                    f"dose_times and dose_amounts must have equal length; got {dose_times_arr.size} and {dose_amounts_arr.size}."
                )
            if not np.all(np.isfinite(dose_amounts_arr)):
                raise ValueError("All dose_amounts values must be finite.")
        else:
            # Repeat scalar Dose at every dose_time
            dose_amounts_arr = np.full(dose_times_arr.size, float(Dose), dtype=float)

        # Validate dose amounts
        if np.any(dose_amounts_arr < 0):
            bad_idx = np.where(dose_amounts_arr < 0)[0]
            raise ValueError(f"dose_amounts has negative value {dose_amounts_arr[bad_idx[0]]:.6g}.")

        return dose_times_arr, dose_amounts_arr, int(dose_times_arr.size)

    # Should not reach here
    raise ValueError("Unhandled dosing specification case.")


# -------------------------
# PK ODE function
# -------------------------
def pk_ode(t: float, y: Sequence[float], ka: float, ke: float, F: float) -> np.ndarray:
    """
    ODE right-hand side for the two-state PK model.
    y[0] = A_gut (mg)
    y[1] = A_central (mg)
    Returns derivatives [dA_gut/dt, dA_central/dt].
    """
    A_gut = float(y[0])
    A_central = float(y[1])
    dA_gut = -ka * A_gut
    dA_central = F * ka * A_gut - ke * A_central
    return np.array([dA_gut, dA_central], dtype=float)


# -------------------------
# Analytical PK reference functions
# -------------------------
def analytical_pk_unequal_rates(
    tau: np.ndarray,
    Dose: float,
    F: float,
    ka: float,
    ke: float,
    V: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Analytical solution for one-compartment oral PK with first-order absorption (ka != ke).

    Parameters
    ----------
    tau : ndarray
        Elapsed time (t - t_start), shape (n,).
    Dose : float
        Single oral dose (mg).
    F : float
        Bioavailability (dimensionless, 0..1).
    ka : float
        Absorption rate constant (1/h).
    ke : float
        Elimination rate constant (1/h).
    V : float
        Volume of distribution (L).

    Returns
    -------
    A_gut : ndarray
        Amount in gut compartment (mg).
    A_central : ndarray
        Amount in central compartment (mg).
    concentration : ndarray
        Plasma concentration (mg/L).

    Notes
    -----
    Uses the closed-form solution for ka != ke:
      A_gut(t) = Dose * exp(-ka * tau)
      A_central(t) = F * Dose * ka / (ka - ke) * (exp(-ke * tau) - exp(-ka * tau))
    """
    tau = np.asarray(tau, dtype=float)
    A_gut = Dose * np.exp(-ka * tau)
    rate_diff = ka - ke
    A_central = F * Dose * ka / rate_diff * (np.exp(-ke * tau) - np.exp(-ka * tau))
    concentration = A_central / V
    return A_gut, A_central, concentration


def analytical_pk_equal_rates(
    tau: np.ndarray,
    Dose: float,
    F: float,
    k: float,
    V: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Analytical solution for one-compartment oral PK with first-order absorption (ka == ke == k).

    Parameters
    ----------
    tau : ndarray
        Elapsed time (t - t_start), shape (n,).
    Dose : float
        Single oral dose (mg).
    F : float
        Bioavailability (dimensionless, 0..1).
    k : float
        Rate constant (ka == ke, 1/h).
    V : float
        Volume of distribution (L).

    Returns
    -------
    A_gut : ndarray
        Amount in gut compartment (mg).
    A_central : ndarray
        Amount in central compartment (mg).
    concentration : ndarray
        Plasma concentration (mg/L).

    Notes
    -----
    Uses the limiting analytical solution as ka -> ke:
      A_gut(t) = Dose * exp(-k * tau)
      A_central(t) = F * Dose * k * tau * exp(-k * tau)
    """
    tau = np.asarray(tau, dtype=float)
    A_gut = Dose * np.exp(-k * tau)
    A_central = F * Dose * k * tau * np.exp(-k * tau)
    concentration = A_central / V
    return A_gut, A_central, concentration


def analytical_pk_repeated_dose(
    time_array: np.ndarray,
    dose_times: np.ndarray,
    dose_amounts: np.ndarray,
    F: float,
    ka: float,
    ke: float,
    V: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Analytical solution for repeated-dose oral PK using superposition.

    Uses the single-dose analytical formulas and superimposes contributions
    from each dose event.

    Parameters
    ----------
    time_array : ndarray
        Times at which to evaluate (absolute times, shape (n,)).
    dose_times : ndarray
        Times of dose administration (shape (m,)).
    dose_amounts : ndarray
        Dose amounts (shape (m,)).
    F : float
        Bioavailability.
    ka : float
        Absorption rate constant (1/h).
    ke : float
        Elimination rate constant (1/h).
    V : float
        Volume of distribution (L).

    Returns
    -------
    A_gut : ndarray
        Total amount in gut (mg), shape (n,).
    A_central : ndarray
        Total amount in central (mg), shape (n,).
    concentration : ndarray
        Total concentration (mg/L), shape (n,).
    """
    time_array = np.asarray(time_array, dtype=float)
    A_gut_total = np.zeros_like(time_array)
    A_central_total = np.zeros_like(time_array)

    # Superpose each dose
    for dose_time, dose_amt in zip(dose_times, dose_amounts):
        elapsed = time_array - dose_time
        # Only include contribution where elapsed >= 0
        valid_mask = elapsed >= -1e-14
        elapsed_valid = np.maximum(elapsed, 0.0)

        if np.isclose(ka, ke, rtol=KE_RTOL, atol=KE_ATOL):
            # Use equal-rate formula
            A_gut_i, A_central_i, _ = analytical_pk_equal_rates(elapsed_valid, dose_amt, F, ka, V)
        else:
            # Use unequal-rate formula
            A_gut_i, A_central_i, _ = analytical_pk_unequal_rates(elapsed_valid, dose_amt, F, ka, ke, V)

        A_gut_total[valid_mask] += A_gut_i[valid_mask]
        A_central_total[valid_mask] += A_central_i[valid_mask]

    concentration = A_central_total / V
    return A_gut_total, A_central_total, concentration


# -------------------------
# PD function: stimulatory sigmoid Emax
# -------------------------
def sigmoid_emax(
    concentration: np.ndarray,
    E0: float,
    Emax: float,
    EC50: float,
    gamma: float,
    conc_neg_tol: float = 0.0,
) -> np.ndarray:
    """
    Compute E(C) = E0 + Emax * C^gamma / (EC50^gamma + C^gamma).

    Works with scalars or arrays (NumPy). Safely handles tiny negative concentrations
    by clipping to zero if abs(value) <= conc_neg_tol; raises if more negative.

    Uses a numerically stable formulation based on the dimensionless ratio x = C / EC50:
      - For x <= 1: z = x^gamma; frac = z / (1 + z)
      - For x > 1: z = x^(-gamma); frac = 1 / (1 + z)

    This avoids unnecessary overflow when computing large powers.

    Parameters
    ----------
    concentration : array-like
        Plasma concentration (mg/L), scalar or ndarray.
    E0 : float
        Baseline effect.
    Emax : float
        Maximum effect (must be >= 0).
    EC50 : float
        Concentration producing 50% effect (must be > 0, mg/L).
    gamma : float
        Hill coefficient (must be > 0).
    conc_neg_tol : float, optional
        Tolerance for clipping tiny negative concentrations to zero (mg/L).
        Default: 0.0.

    Returns
    -------
    effect : ndarray
        Pharmacodynamic effect (same shape as concentration).

    Raises
    ------
    ValueError
        If conc_neg_tol < 0, or if concentration has values more negative than -conc_neg_tol.
    """
    C = np.asarray(concentration, dtype=float)

    # Validate and handle tiny negative concentrations
    if conc_neg_tol < 0:
        raise ValueError("conc_neg_tol must be nonnegative.")
    neg_mask = C < 0.0
    if np.any(neg_mask):
        max_neg = float(np.min(C[neg_mask]))
        if max_neg < -conc_neg_tol:
            raise ValueError(
                f"Concentration has values more negative ({max_neg:.3g}) than allowed tolerance {-conc_neg_tol:.3g}."
            )
        # Clip tiny negatives to zero for stable fractional powers
        C = np.maximum(C, 0.0)

    # Validate PD parameters
    if EC50 <= 0:
        raise ValueError(f"EC50 must be > 0; got {EC50}.")
    if gamma <= 0:
        raise ValueError(f"gamma must be > 0; got {gamma}.")

    # Compute dimensionless concentration ratio
    x = C / EC50

    # Numerically stable Hill fraction computation
    # For x <= 1: z = x^gamma, frac = z / (1 + z)
    # For x > 1: z = x^(-gamma), frac = 1 / (1 + z)
    frac = np.zeros_like(C, dtype=float)

    # Case 1: x <= 1
    mask_low = x <= 1.0
    if np.any(mask_low):
        z_low = np.power(x[mask_low], gamma)
        frac[mask_low] = z_low / (1.0 + z_low)

    # Case 2: x > 1
    mask_high = x > 1.0
    if np.any(mask_high):
        z_high = np.power(x[mask_high], -gamma)
        frac[mask_high] = 1.0 / (1.0 + z_high)

    return float(E0) + float(Emax) * frac


# -------------------------
# Piecewise repeated-dose integration
# -------------------------
def _integrate_segment(
    t_start_seg: float,
    t_end_seg: float,
    y_init: np.ndarray,
    t_eval_segment: Optional[np.ndarray],
    ka: float,
    ke: float,
    F: float,
    method: str,
    rtol: float,
    atol: float,
    max_step: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Integrate a single ODE segment and return time, A_gut, A_central.

    Returns
    -------
    t_seg : ndarray
    A_gut_seg : ndarray
    A_central_seg : ndarray
    """
    sol = solve_ivp(
        fun=lambda t, y: pk_ode(t, y, ka=ka, ke=ke, F=F),
        t_span=(float(t_start_seg), float(t_end_seg)),
        y0=y_init,
        method=method,
        t_eval=t_eval_segment,
        rtol=rtol,
        atol=atol,
        max_step=max_step,
    )

    if sol.status != 0 or not sol.success:
        raise RuntimeError(f"ODE solver failed: message='{sol.message}', status={sol.status}")

    t_seg = np.asarray(sol.t, dtype=float)
    A_gut_seg = np.asarray(sol.y[0, :], dtype=float)
    A_central_seg = np.asarray(sol.y[1, :], dtype=float)

    if not (np.all(np.isfinite(t_seg)) and np.all(np.isfinite(A_gut_seg)) and np.all(np.isfinite(A_central_seg))):
        raise RuntimeError("Integration produced non-finite values.")

    return t_seg, A_gut_seg, A_central_seg


# -------------------------
# Simulation function
# -------------------------
def simulate_pkpd(
    Dose: float,
    F: float,
    ka: float,
    V: float,
    CL: float,
    E0: float,
    Emax: float,
    EC50: float,
    gamma: float,
    t_start: float = 0.0,
    t_end: float = 48.0,
    t_eval: Optional[Sequence[float]] = None,
    ke_supplied: Optional[float] = None,
    method: str = DEFAULT_RK_METHOD,
    rtol: float = DEFAULT_RTOL,
    atol: float = DEFAULT_ATOL,
    tau: Optional[float] = None,
    n_doses: Optional[int] = None,
    dose_times: Optional[Sequence[float]] = None,
    dose_amounts: Optional[Sequence[float]] = None,
) -> Dict[str, Any]:
    """
    Simulate the two-state PK model and PD effect over the given time range.
    Supports single-dose and repeated-dose oral regimens.

    Parameters
    ----------
    Dose : float
        Single dose amount for legacy call or default for explicit schedule (mg).
    F : float
        Bioavailability (0..1).
    ka : float
        Absorption rate constant (1/h).
    V : float
        Volume of distribution (L).
    CL : float
        Clearance (L/h).
    E0 : float
        Baseline pharmacodynamic effect.
    Emax : float
        Maximum pharmacodynamic effect (mg).
    EC50 : float
        Concentration producing 50% effect (mg/L).
    gamma : float
        Hill coefficient.
    t_start : float, optional
        Start time (h). Default: 0.0.
    t_end : float, optional
        End time (h). Default: 48.0.
    t_eval : sequence of float, optional
        Times at which to return solution. If None, uses 0.05 h spacing.
    ke_supplied : float, optional
        Pre-computed ke for validation.
    method : str, optional
        ODE solver method. Default: "RK45".
    rtol : float, optional
        Relative tolerance. Default: 1e-8.
    atol : float, optional
        Absolute tolerance. Default: 1e-10.
    tau : float, optional
        Dosing interval for regular regimen (h).
    n_doses : int, optional
        Number of doses for regular regimen.
    dose_times : sequence of float, optional
        Explicit dose times (h).
    dose_amounts : sequence of float, optional
        Explicit dose amounts (mg); defaults to Dose if not provided.

    Returns
    -------
    results : dict
        Keys: "time", "A_gut", "A_central", "concentration", "effect", "ke", "units", "meta"
        - time : ndarray (h)
        - A_gut : ndarray (mg)
        - A_central : ndarray (mg)
        - concentration : ndarray (mg/L)
        - effect : ndarray (user-defined)
        - ke : float (1/h)
        - units : dict
        - meta : dict (includes dosing information)

    Dosing convention:
        At exact dose time t_i, returned A_gut is post-dose state.
        A_central, concentration, effect remain continuous through events.
    """
    # Validate inputs and compute derived ke and negativity tolerance
    ke, base_neg_tol = validate_parameters(
        Dose=Dose,
        F=F,
        ka=ka,
        V=V,
        CL=CL,
        EC50=EC50,
        gamma=gamma,
        Emax=Emax,
        E0=E0,
        t_start=t_start,
        t_end=t_end,
        t_eval=t_eval,
        ke_supplied=ke_supplied,
    )

    # Validate solver controls
    validate_solver_controls(rtol=rtol, atol=atol)

    # Build and validate dosing schedule
    dose_times_arr, dose_amounts_arr, n_doses_total = build_or_validate_dosing_schedule(
        Dose=Dose,
        tau=tau,
        n_doses=n_doses,
        dose_times=dose_times,
        dose_amounts=dose_amounts,
        t_start=t_start,
        t_end=t_end,
    )

    # Scale negativity tolerance for repeated dosing
    max_dose = float(np.max(dose_amounts_arr))
    neg_tol = max(base_neg_tol, 1e-8 * max_dose)

    # Build evaluation grid if not provided: spacing 0.05 h by default
    if t_eval is None:
        dt = 0.05  # hours
        t_eval_grid = np.arange(t_start, t_end + dt / 2.0, dt, dtype=float)
    else:
        t_eval_grid = np.asarray(t_eval, dtype=float)

    # Max step policy
    fastest_rate = max(ka, ke)
    if fastest_rate <= 0.0:
        max_step_by_rate = np.inf
    else:
        max_step_by_rate = 0.1 / fastest_rate

    if t_eval_grid.size == 1:
        eval_spacing = np.inf
    else:
        eval_spacing = float(np.min(np.diff(t_eval_grid)))

    max_step = float(min(eval_spacing, max_step_by_rate))
    if not np.isfinite(max_step) or max_step <= 0:
        max_step = (t_end - t_start) / 100.0

    # ---- Piecewise integration ----
    accumulated_time = []
    accumulated_A_gut = []
    accumulated_A_central = []

    # Current state at start of each segment
    y_current = np.array([0.0, 0.0], dtype=float)
    t_current = t_start

    for dose_idx in range(n_doses_total):
        t_dose = dose_times_arr[dose_idx]
        dose_amt = dose_amounts_arr[dose_idx]

        # Integrate from t_current to t_dose
        if t_dose > t_current + 1e-14:
            # Find t_eval points in (t_current, t_dose)
            t_eval_segment = t_eval_grid[(t_eval_grid > t_current + EVENT_TIME_TOL) & (t_eval_grid < t_dose - EVENT_TIME_TOL)]

            t_seg, A_gut_seg, A_central_seg = _integrate_segment(
                t_current,
                t_dose,
                y_current,
                t_eval_segment,
                ka=ka,
                ke=ke,
                F=F,
                method=method,
                rtol=rtol,
                atol=atol,
                max_step=max_step,
            )

            accumulated_time.extend(t_seg)
            accumulated_A_gut.extend(A_gut_seg)
            accumulated_A_central.extend(A_central_seg)

            # State just before dose
            y_current[0] = A_gut_seg[-1]
            y_current[1] = A_central_seg[-1]
        elif t_dose < t_current - 1e-14:
            # Dose is in the past (e.g., first dose is not at t_start)
            # Should not occur after validation, but handle gracefully
            pass

        # Apply dose (discontinuous jump to A_gut only)
        y_current[0] += dose_amt
        t_current = t_dose

        # Add post-dose state at exact t_dose
        accumulated_time.append(float(t_dose))
        accumulated_A_gut.append(float(y_current[0]))
        accumulated_A_central.append(float(y_current[1]))

    # Integrate from last dose to t_end
    if t_end > t_current + 1e-14:
        t_eval_segment = t_eval_grid[(t_eval_grid > t_current + EVENT_TIME_TOL) & (t_eval_grid <= t_end + 1e-14)]

        t_seg, A_gut_seg, A_central_seg = _integrate_segment(
            t_current,
            t_end,
            y_current,
            t_eval_segment,
            ka=ka,
            ke=ke,
            F=F,
            method=method,
            rtol=rtol,
            atol=atol,
            max_step=max_step,
        )

        accumulated_time.extend(t_seg)
        accumulated_A_gut.extend(A_gut_seg)
        accumulated_A_central.extend(A_central_seg)

    # Convert to arrays and remove duplicates
    time = np.array(accumulated_time, dtype=float)
    A_gut = np.array(accumulated_A_gut, dtype=float)
    A_central = np.array(accumulated_A_central, dtype=float)

    # Sort and remove duplicates (keep post-dose value at event times)
    if len(time) > 1:
        sort_idx = np.argsort(time)
        time = time[sort_idx]
        A_gut = A_gut[sort_idx]
        A_central = A_central[sort_idx]

        # Remove duplicates: keep later (post-dose) value
        unique_mask = np.concatenate(([True], np.diff(time) > EVENT_TIME_TOL))
        time = time[unique_mask]
        A_gut = A_gut[unique_mask]
        A_central = A_central[unique_mask]

    # Validate accumulated state
    min_A_gut = float(np.min(A_gut)) if A_gut.size > 0 else 0.0
    min_A_central = float(np.min(A_central)) if A_central.size > 0 else 0.0
    if min_A_gut < -neg_tol or min_A_central < -neg_tol:
        raise RuntimeError(
            f"Accumulated state has materially negative values: min(A_gut)={min_A_gut:.3g}, min(A_central)={min_A_central:.3g}; "
            f"negativity tolerance={neg_tol:.3g}."
        )

    # Clip small negatives
    A_gut_clipped = np.maximum(A_gut, 0.0)
    A_central_clipped = np.maximum(A_central, 0.0)

    # Compute concentration
    concentration = A_central_clipped / float(V)

    if not np.all(np.isfinite(concentration)):
        raise RuntimeError("Non-finite concentration values encountered.")
    if np.min(concentration) < -1e-14:
        raise RuntimeError("Concentration has negative values beyond minimal numerical noise.")

    # Compute effect from total concentration
    effect = sigmoid_emax(concentration, E0=E0, Emax=Emax, EC50=EC50, gamma=gamma, conc_neg_tol=1e-14)

    # Package results with units and metadata
    results = {
        "time": time,  # h
        "A_gut": A_gut_clipped,  # mg
        "A_central": A_central_clipped,  # mg
        "concentration": concentration,  # mg/L
        "effect": effect,  # effect units
        "ke": ke,  # 1/h
        "units": {
            "time": "h",
            "amount": "mg",
            "volume": "L",
            "concentration": "mg/L",
            "ke": "1/h",
            "effect": "user-defined units",
        },
        "meta": {
            "method": method,
            "rtol": rtol,
            "atol": atol,
            "max_step": max_step,
            "negativity_tolerance_amount_mg": neg_tol,
            "ke_consistency_rtol": KE_RTOL,
            "ke_consistency_atol": KE_ATOL,
            "dosing": {
                "route": "oral",
                "n_doses": int(n_doses_total),
                "dose_times": dose_times_arr.tolist(),
                "dose_amounts": dose_amounts_arr.tolist(),
                "event_state_convention": "post-dose A_gut; continuous A_central/concentration/effect",
            },
            "bioavailability_convention": "F applied in absorption flux F*ka*A_gut; CL and V are systemic (not apparent)",
        },
    }
    return results


def summarize_pk(results: Dict[str, Any]) -> Dict[str, Any]:
    """
    Compute PK summary statistics from simulation results.

    Parameters
    ----------
    results : dict
        Output from simulate_pkpd.

    Returns
    -------
    summary : dict
        Keys: Cmax, Tmax, Cmax_last_interval, Tmax_last_interval, Ctrough_last_interval, AUC_last_interval
        Values are numeric or None if not mathematically defined.
    """
    time = results["time"]
    concentration = results["concentration"]
    dose_info = results["meta"]["dosing"]
    n_doses = dose_info["n_doses"]
    dose_times = np.array(dose_info["dose_times"], dtype=float)

    summary = {}

    # Overall Cmax and Tmax
    if concentration.size > 0:
        max_idx = np.argmax(concentration)
        summary["Cmax"] = float(concentration[max_idx])
        summary["Tmax"] = float(time[max_idx])
    else:
        summary["Cmax"] = None
        summary["Tmax"] = None

    # Last-interval metrics (if defined)
    if n_doses >= 2:
        tau_last = float(dose_times[-1] - dose_times[-2])
        t_last_dose = float(dose_times[-1])
        t_last_interval_end = t_last_dose + tau_last

        # If final interval extends beyond t_end, mark unavailable
        t_end = float(time[-1])
        if t_last_interval_end > t_end + EVENT_TIME_TOL:
            summary["Cmax_last_interval"] = None
            summary["Tmax_last_interval"] = None
            summary["Ctrough_last_interval"] = None
            summary["AUC_last_interval"] = None
        else:
            # Find concentration in last interval
            mask_last = (time >= t_last_dose - EVENT_TIME_TOL) & (time <= t_last_interval_end + EVENT_TIME_TOL)
            if np.any(mask_last):
                C_last = concentration[mask_last]
                t_last = time[mask_last]

                max_idx_last = np.argmax(C_last)
                summary["Cmax_last_interval"] = float(C_last[max_idx_last])
                summary["Tmax_last_interval"] = float(t_last[max_idx_last])
                summary["Ctrough_last_interval"] = float(C_last[-1])  # at end of interval

                # Trapezoidal AUC
                auc_last = float(np.trapz(C_last, t_last))
                summary["AUC_last_interval"] = auc_last
            else:
                summary["Cmax_last_interval"] = None
                summary["Tmax_last_interval"] = None
                summary["Ctrough_last_interval"] = None
                summary["AUC_last_interval"] = None
    else:
        summary["Cmax_last_interval"] = None
        summary["Tmax_last_interval"] = None
        summary["Ctrough_last_interval"] = None
        summary["AUC_last_interval"] = None

    return summary


# -------------------------
# Plotting
# -------------------------
def plot_pkpd(results: Dict[str, Any], title_suffix: str = "", show_dose_markers: bool = True) -> None:
    """
    Plot concentration-time and effect-time from simulation results dictionary.
    Optionally overlay dose event markers.

    Parameters
    ----------
    results : dict
        Output from simulate_pkpd.
    title_suffix : str, optional
        Suffix for plot titles.
    show_dose_markers : bool, optional
        If True, mark dose times on concentration plot. Default: True.
    """
    t = results["time"]
    C = results["concentration"]
    E = results["effect"]
    units = results.get("units", {})
    time_unit = units.get("time", "h")
    conc_unit = units.get("concentration", "mg/L")
    eff_unit = units.get("effect", "units")

    fig, axes = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
    axes[0].plot(t, C, color="C0", lw=1.5, label="Concentration")
    axes[0].set_ylabel(f"Concentration ({conc_unit})", fontsize=10)
    axes[0].set_title(f"Concentration vs Time {title_suffix}".strip())
    axes[0].grid(True)

    # Add dose markers if requested
    if show_dose_markers:
        dose_info = results["meta"].get("dosing", {})
        dose_times_list = dose_info.get("dose_times", [])
        if dose_times_list:
            for dt in dose_times_list:
                axes[0].axvline(dt, color="red", linestyle="--", alpha=0.5, linewidth=1)
            axes[0].legend()

    axes[1].plot(t, E, color="C1", lw=1.5, label="Effect")
    axes[1].set_xlabel(f"Time ({time_unit})", fontsize=10)
    axes[1].set_ylabel(f"Effect ({eff_unit})", fontsize=10)
    axes[1].set_title(f"Pharmacodynamic Effect vs Time {title_suffix}".strip())
    axes[1].grid(True)
    axes[1].legend()

    plt.tight_layout()
    plt.show()


# -------------------------
# Runnable demonstration
# -------------------------
if __name__ == "__main__":
    print("=" * 70)
    print("PK/PD Simulator with Single-Dose and Repeated-Dose Support")
    print("=" * 70)
    print()

    # ---- Example 1: Legacy single-dose ----
    print("EXAMPLE 1: Legacy Single-Dose Simulation")
    print("-" * 70)
    Dose = 100.0  # mg
    F = 0.6  # fraction (dimensionless)
    ka = 1.0  # 1/h
    V = 20.0  # L
    CL = 1.0  # L/h -> ke = 0.05 1/h
    E0 = 0.0  # baseline effect units
    Emax = 100.0  # effect units
    EC50 = 2.0  # mg/L
    gamma = 1.5  # Hill coefficient

    t_start = 0.0
    t_end = 48.0
    dt = 0.05
    t_eval = np.arange(t_start, t_end + dt / 2.0, dt, dtype=float)

    results_single = simulate_pkpd(
        Dose=Dose,
        F=F,
        ka=ka,
        V=V,
        CL=CL,
        E0=E0,
        Emax=Emax,
        EC50=EC50,
        gamma=gamma,
        t_start=t_start,
        t_end=t_end,
        t_eval=t_eval,
    )

    ke_computed = results_single["ke"]
    ke_expected = CL / V
    print(f"ke (computed) = {ke_computed:.8g} 1/h, ke (CL/V) = {ke_expected:.8g} 1/h")

    summary_single = summarize_pk(results_single)
    print(f"Cmax = {summary_single['Cmax']:.6g} mg/L")
    print(f"Tmax = {summary_single['Tmax']:.6g} h")
    print()

    # Validation checks
    assert np.isclose(ke_computed, ke_expected, rtol=KE_RTOL, atol=KE_ATOL), "ke inconsistency."
    assert np.all(np.isfinite(results_single["A_gut"])), "Non-finite A_gut."
    assert np.all(np.isfinite(results_single["A_central"])), "Non-finite A_central."
    print("✓ Legacy single-dose validation passed")
    print()

    # ---- Example 2: Repeated-dose ----
    print("EXAMPLE 2: Repeated-Dose Simulation (Regular Regimen)")
    print("-" * 70)
    Dose_repeat = 100.0  # mg
    tau = 12.0  # h
    n_doses_repeat = 8
    t_end_repeat = 96.0

    results_repeat = simulate_pkpd(
        Dose=Dose_repeat,
        F=F,
        ka=ka,
        V=V,
        CL=CL,
        E0=E0,
        Emax=Emax,
        EC50=EC50,
        gamma=gamma,
        t_start=t_start,
        t_end=t_end_repeat,
        tau=tau,
        n_doses=n_doses_repeat,
    )

    summary_repeat = summarize_pk(results_repeat)
    print(f"Number of doses administered: {results_repeat['meta']['dosing']['n_doses']}")
    print(f"Dosing interval (tau): {tau} h")
    print(f"Overall Cmax = {summary_repeat['Cmax']:.6g} mg/L at Tmax = {summary_repeat['Tmax']:.6g} h")
    if summary_repeat["Cmax_last_interval"] is not None:
        print(f"Last-interval Cmax = {summary_repeat['Cmax_last_interval']:.6g} mg/L")
        print(f"Last-interval Ctrough = {summary_repeat['Ctrough_last_interval']:.6g} mg/L")
        print(f"Last-interval AUC = {summary_repeat['AUC_last_interval']:.6g} mg·h/L")
    print()

    # Analytical reference for repeated dose
    dose_times_arr = np.array(results_repeat["meta"]["dosing"]["dose_times"], dtype=float)
    dose_amounts_arr = np.array(results_repeat["meta"]["dosing"]["dose_amounts"], dtype=float)
    A_gut_analytical, A_central_analytical, C_analytical = analytical_pk_repeated_dose(
        results_repeat["time"], dose_times_arr, dose_amounts_arr, F, ka, ke_expected, V
    )

    # Compare numerical vs analytical at a few points
    max_deviation = float(np.max(np.abs(results_repeat["concentration"] - C_analytical)))
    print(f"Maximum absolute deviation (numerical vs analytical): {max_deviation:.3g} mg/L")
    print()

    assert np.all(np.isfinite(results_repeat["A_gut"])), "Non-finite A_gut in repeated dose."
    assert np.all(np.isfinite(results_repeat["A_central"])), "Non-finite A_central in repeated dose."
    print("✓ Repeated-dose simulation validation passed")
    print()

    print("=" * 70)
    print("All demonstrations completed successfully.")
    print("=" * 70)
