# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ffxu2RxDDwnnTFIK5KCcaDgwyS2evOqQ
"""

# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Maowu1dnATetSGI3d_qj8Edv9KzpN2bg
"""

"""
One-compartment oral PK with first-order absorption and direct stimulatory sigmoid Emax PD.

Units:
 - time: hours (h)
 - amount: milligrams (mg)
 - volume: liters (L)
 - clearance: L/h
 - concentration: mg/L
 - ka, ke: 1/h
 - F: dimensionless (0..1)
 - effect units: user-defined (E0, Emax)

Deterministic, single-dose base implementation with explicit validation and diagnostics.
"""
from typing import Dict, Optional, Sequence, Tuple
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# -------------------------
# Default numerical options
# -------------------------
DEFAULT_RK_METHOD = "RK45"
DEFAULT_RTOL = 1e-8
DEFAULT_ATOL = 1e-10
# ke consistency tolerances
KE_RTOL = 1e-8
KE_ATOL = 1e-12


# -------------------------
# Validation utilities
# -------------------------
def _is_finite_number(x: float) -> bool:
    return np.isfinite(x)


def validate_parameters(
    Dose: float,
    F: float,
    ka: float,
    V: float,
    CL: float,
    EC50: float,
    gamma: float,
    Emax: float,
    E0: float,
    t_start: float,
    t_end: float,
    t_eval: Optional[Sequence[float]],
    ke_supplied: Optional[float] = None,
) -> Tuple[float, float]:
    """
    Validate inputs and compute ke = CL / V.
    Raises ValueError with informative messages for invalid inputs.
    Returns computed ke and the negativity tolerance (abs, in mg).
    """
    # Basic numeric checks
    params = dict(Dose=Dose, F=F, ka=ka, V=V, CL=CL, EC50=EC50, gamma=gamma, Emax=Emax, E0=E0, t_start=t_start, t_end=t_end)
    for name, val in params.items():
        if not _is_finite_number(val):
            raise ValueError(f"Parameter {name} must be a finite number; got {val!r}.")

    if Dose < 0:
        raise ValueError("Dose must be >= 0.")
    if not (0.0 <= F <= 1.0):
        raise ValueError("F (bioavailability) must satisfy 0 <= F <= 1.")
    if ka <= 0.0:
        raise ValueError("ka must be > 0 (1/h).")
    if V <= 0.0:
        raise ValueError("V must be > 0 (L).")
    if CL <= 0.0:
        raise ValueError("CL must be > 0 (L/h).")
    if EC50 <= 0.0:
        raise ValueError("EC50 must be > 0 (mg/L).")
    if gamma <= 0.0:
        raise ValueError("gamma must be > 0 (dimensionless).")
    if Emax < 0.0:
        raise ValueError("Emax must be >= 0 for the stimulatory model.")
    # time checks
    if not (_is_finite_number(t_start) and _is_finite_number(t_end)):
        raise ValueError("t_start and t_end must be finite numbers.")
    if t_end <= t_start:
        raise ValueError("t_end must be greater than t_start.")
    if t_eval is not None:
        t_eval_arr = np.asarray(t_eval, dtype=float)
        if t_eval_arr.ndim != 1:
            raise ValueError("t_eval must be a 1-D sequence of times.")
        if t_eval_arr.size < 1:
            raise ValueError("t_eval must have at least 1 element.")
        if not np.all(np.isfinite(t_eval_arr)):
            raise ValueError("All t_eval values must be finite.")
        if not (t_eval_arr[0] >= t_start - 1e-14 and t_eval_arr[-1] <= t_end + 1e-14):
            raise ValueError("t_eval values must lie within [t_start, t_end].")
        if t_eval_arr.size > 1:
            if not np.all(np.diff(t_eval_arr) > 0):
                raise ValueError("t_eval must be strictly increasing (no duplicates).")
    # compute ke and compare if supplied
    ke = float(CL / V)
    if ke_supplied is not None:
        if not _is_finite_number(ke_supplied):
            raise ValueError("Supplied ke must be finite.")
        if not np.isclose(ke, ke_supplied, rtol=KE_RTOL, atol=KE_ATOL):
            raise ValueError(
                f"Supplied ke={ke_supplied:.12g} is inconsistent with CL/V={ke:.12g} "
                f"(tolerances rtol={KE_RTOL}, atol={KE_ATOL})."
            )
    # negativity tolerance relative to problem scale (amount units: mg)
    neg_tol = max(1e-12, 1e-8 * max(1.0, float(Dose)))
    return ke, neg_tol


def validate_solver_controls(
    rtol: float,
    atol: float,
) -> None:
    """
    Validate that ODE solver tolerances are scalar, finite, and strictly positive.
    Raises ValueError for invalid inputs.
    """
    if not _is_finite_number(rtol):
        raise ValueError(f"rtol must be finite; got {rtol!r}.")
    if not _is_finite_number(atol):
        raise ValueError(f"atol must be finite; got {atol!r}.")
    if rtol <= 0.0:
        raise ValueError(f"rtol must be > 0; got {rtol}.")
    if atol <= 0.0:
        raise ValueError(f"atol must be > 0; got {atol}.")


# -------------------------
# PK ODE function
# -------------------------
def pk_ode(t: float, y: Sequence[float], ka: float, ke: float, F: float) -> np.ndarray:
    """
    ODE right-hand side for the two-state PK model.
    y[0] = A_gut (mg)
    y[1] = A_central (mg)
    Returns derivatives [dA_gut/dt, dA_central/dt].
    """
    A_gut = float(y[0])
    A_central = float(y[1])
    dA_gut = -ka * A_gut
    dA_central = F * ka * A_gut - ke * A_central
    return np.array([dA_gut, dA_central], dtype=float)


# -------------------------
# Analytical PK reference functions
# -------------------------
def analytical_pk_unequal_rates(
    tau: np.ndarray,
    Dose: float,
    F: float,
    ka: float,
    ke: float,
    V: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Analytical solution for one-compartment oral PK with first-order absorption (ka != ke).

    Parameters
    ----------
    tau : ndarray
        Elapsed time (t - t_start), shape (n,).
    Dose : float
        Single oral dose (mg).
    F : float
        Bioavailability (dimensionless, 0..1).
    ka : float
        Absorption rate constant (1/h).
    ke : float
        Elimination rate constant (1/h).
    V : float
        Volume of distribution (L).

    Returns
    -------
    A_gut : ndarray
        Amount in gut compartment (mg).
    A_central : ndarray
        Amount in central compartment (mg).
    concentration : ndarray
        Plasma concentration (mg/L).

    Notes
    -----
    Uses the closed-form solution for ka != ke:
      A_gut(t) = Dose * exp(-ka * tau)
      A_central(t) = F * Dose * ka / (ka - ke) * (exp(-ke * tau) - exp(-ka * tau))
    """
    tau = np.asarray(tau, dtype=float)
    A_gut = Dose * np.exp(-ka * tau)
    rate_diff = ka - ke
    A_central = F * Dose * ka / rate_diff * (np.exp(-ke * tau) - np.exp(-ka * tau))
    concentration = A_central / V
    return A_gut, A_central, concentration


def analytical_pk_equal_rates(
    tau: np.ndarray,
    Dose: float,
    F: float,
    k: float,
    V: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Analytical solution for one-compartment oral PK with first-order absorption (ka == ke == k).

    Parameters
    ----------
    tau : ndarray
        Elapsed time (t - t_start), shape (n,).
    Dose : float
        Single oral dose (mg).
    F : float
        Bioavailability (dimensionless, 0..1).
    k : float
        Rate constant (ka == ke, 1/h).
    V : float
        Volume of distribution (L).

    Returns
    -------
    A_gut : ndarray
        Amount in gut compartment (mg).
    A_central : ndarray
        Amount in central compartment (mg).
    concentration : ndarray
        Plasma concentration (mg/L).

    Notes
    -----
    Uses the limiting analytical solution as ka -> ke:
      A_gut(t) = Dose * exp(-k * tau)
      A_central(t) = F * Dose * k * tau * exp(-k * tau)
    """
    tau = np.asarray(tau, dtype=float)
    A_gut = Dose * np.exp(-k * tau)
    A_central = F * Dose * k * tau * np.exp(-k * tau)
    concentration = A_central / V
    return A_gut, A_central, concentration


# -------------------------
# PD function: stimulatory sigmoid Emax
# -------------------------
def sigmoid_emax(
    concentration: np.ndarray,
    E0: float,
    Emax: float,
    EC50: float,
    gamma: float,
    conc_neg_tol: float = 0.0,
) -> np.ndarray:
    """
    Compute E(C) = E0 + Emax * C^gamma / (EC50^gamma + C^gamma).

    Works with scalars or arrays (NumPy). Safely handles tiny negative concentrations
    by clipping to zero if abs(value) <= conc_neg_tol; raises if more negative.

    Uses a numerically stable formulation based on the dimensionless ratio x = C / EC50:
      - For x <= 1: z = x^gamma; frac = z / (1 + z)
      - For x > 1: z = x^(-gamma); frac = 1 / (1 + z)

    This avoids unnecessary overflow when computing large powers.

    Parameters
    ----------
    concentration : array-like
        Plasma concentration (mg/L), scalar or ndarray.
    E0 : float
        Baseline effect.
    Emax : float
        Maximum effect (must be >= 0).
    EC50 : float
        Concentration producing 50% effect (must be > 0, mg/L).
    gamma : float
        Hill coefficient (must be > 0).
    conc_neg_tol : float, optional
        Tolerance for clipping tiny negative concentrations to zero (mg/L).
        Default: 0.0.

    Returns
    -------
    effect : ndarray
        Pharmacodynamic effect (same shape as concentration).

    Raises
    ------
    ValueError
        If conc_neg_tol < 0, or if concentration has values more negative than -conc_neg_tol.
    """
    C = np.asarray(concentration, dtype=float)

    # Validate and handle tiny negative concentrations
    if conc_neg_tol < 0:
        raise ValueError("conc_neg_tol must be nonnegative.")
    neg_mask = C < 0.0
    if np.any(neg_mask):
        max_neg = float(np.min(C[neg_mask]))
        if max_neg < -conc_neg_tol:
            raise ValueError(
                f"Concentration has values more negative ({max_neg:.3g}) than allowed tolerance {-conc_neg_tol:.3g}."
            )
        # Clip tiny negatives to zero for stable fractional powers
        C = np.maximum(C, 0.0)

    # Validate PD parameters
    if EC50 <= 0:
        raise ValueError(f"EC50 must be > 0; got {EC50}.")
    if gamma <= 0:
        raise ValueError(f"gamma must be > 0; got {gamma}.")

    # Compute dimensionless concentration ratio
    x = C / EC50

    # Numerically stable Hill fraction computation
    # For x <= 1: z = x^gamma, frac = z / (1 + z)
    # For x > 1: z = x^(-gamma), frac = 1 / (1 + z)
    frac = np.zeros_like(C, dtype=float)

    # Case 1: x <= 1
    mask_low = x <= 1.0
    if np.any(mask_low):
        z_low = np.power(x[mask_low], gamma)
        frac[mask_low] = z_low / (1.0 + z_low)

    # Case 2: x > 1
    mask_high = x > 1.0
    if np.any(mask_high):
        z_high = np.power(x[mask_high], -gamma)
        frac[mask_high] = 1.0 / (1.0 + z_high)

    return float(E0) + float(Emax) * frac


# -------------------------
# Simulation function
# -------------------------
def simulate_pkpd(
    Dose: float,
    F: float,
    ka: float,
    V: float,
    CL: float,
    E0: float,
    Emax: float,
    EC50: float,
    gamma: float,
    t_start: float = 0.0,
    t_end: float = 48.0,
    t_eval: Optional[Sequence[float]] = None,
    ke_supplied: Optional[float] = None,
    method: str = DEFAULT_RK_METHOD,
    rtol: float = DEFAULT_RTOL,
    atol: float = DEFAULT_ATOL,
) -> Dict[str, np.ndarray]:
    """
    Simulate the two-state PK model and PD effect over the given time range.

    Returns a dict with keys:
      "time", "A_gut", "A_central", "concentration", "effect", "ke", "units"
    """
    # Validate inputs and compute derived ke and negativity tolerance
    ke, neg_tol = validate_parameters(
        Dose=Dose,
        F=F,
        ka=ka,
        V=V,
        CL=CL,
        EC50=EC50,
        gamma=gamma,
        Emax=Emax,
        E0=E0,
        t_start=t_start,
        t_end=t_end,
        t_eval=t_eval,
        ke_supplied=ke_supplied,
    )

    # Validate solver controls
    validate_solver_controls(rtol=rtol, atol=atol)

    # Build evaluation grid if not provided: spacing 0.05 h by default
    if t_eval is None:
        dt = 0.05  # hours
        t_eval = np.arange(t_start, t_end + dt / 2.0, dt, dtype=float)
    else:
        t_eval = np.asarray(t_eval, dtype=float)

    # Max step policy:
    # Choose max_step no larger than the evaluation spacing and no larger than a fraction
    # of the fastest PK timescale. Fastest rate = max(ka, ke); timescale = 1/fastest_rate.
    fastest_rate = max(ka, ke)
    if fastest_rate <= 0.0:
        # degenerate; fall back to evaluation spacing
        max_step_by_rate = np.inf
    else:
        max_step_by_rate = 0.1 / fastest_rate  # 0.1 of the fastest timescale

    # Handle single-element t_eval
    if t_eval.size == 1:
        eval_spacing = np.inf
    else:
        eval_spacing = float(np.min(np.diff(t_eval)))

    max_step = float(min(eval_spacing, max_step_by_rate))

    # Ensure max_step is finite and positive
    if not np.isfinite(max_step) or max_step <= 0:
        max_step = (t_end - t_start) / 100.0

    # initial conditions according to base dosing convention:
    # A_gut(0) = Dose, A_central(0) = 0
    y0 = np.array([float(Dose), 0.0], dtype=float)

    # Integrate ODE
    sol = solve_ivp(
        fun=lambda t, y: pk_ode(t, y, ka=ka, ke=ke, F=F),
        t_span=(float(t_start), float(t_end)),
        y0=y0,
        method=method,
        t_eval=t_eval,
        rtol=rtol,
        atol=atol,
        max_step=max_step,
    )

    # Diagnostics on solver result
    if sol.status != 0 or not sol.success:
        raise RuntimeError(f"ODE solver failed: message='{sol.message}', status={sol.status}")

    # Post-process states
    A_gut = np.asarray(sol.y[0, :], dtype=float)
    A_central = np.asarray(sol.y[1, :], dtype=float)
    time = np.asarray(sol.t, dtype=float)

    # Finite checks
    if not (np.all(np.isfinite(A_gut)) and np.all(np.isfinite(A_central)) and np.all(np.isfinite(time))):
        raise RuntimeError("Integration produced non-finite values in states or time.")

    # Negative-state policy:
    # Clip tiny negative amounts (within neg_tol) for derived outputs, but raise if any state < -neg_tol
    min_A_gut = float(np.min(A_gut))
    min_A_central = float(np.min(A_central))
    if min_A_gut < -neg_tol or min_A_central < -neg_tol:
        raise RuntimeError(
            f"Solver produced materially negative state(s): min(A_gut)={min_A_gut:.3g}, min(A_central)={min_A_central:.3g}; "
            f"negativity tolerance={neg_tol:.3g}."
        )
    # For downstream outputs, clip small negatives to zero
    A_gut_clipped = np.maximum(A_gut, 0.0)
    A_central_clipped = np.maximum(A_central, 0.0)

    # Concentration (mg/L)
    concentration = A_central_clipped / float(V)

    # Concentration nonnegativity check (allow tiny negatives handled above)
    if not np.all(np.isfinite(concentration)):
        raise RuntimeError("Non-finite concentration values encountered.")
    if np.min(concentration) < -1e-14:
        # numerical paranoia; should not occur because we clipped amounts
        raise RuntimeError("Concentration has negative values beyond minimal numerical noise.")

    # Compute effect
    effect = sigmoid_emax(concentration, E0=E0, Emax=Emax, EC50=EC50, gamma=gamma, conc_neg_tol=1e-14)

    # Package results with units metadata
    results = {
        "time": time,  # h
        "A_gut": A_gut_clipped,  # mg
        "A_central": A_central_clipped,  # mg
        "concentration": concentration,  # mg/L
        "effect": effect,  # effect units
        "ke": ke,  # 1/h
        "units": {
            "time": "h",
            "amount": "mg",
            "volume": "L",
            "concentration": "mg/L",
            "ke": "1/h",
            "effect": "user-defined units",
        },
        # metadata for reproducibility
        "meta": {
            "method": method,
            "rtol": rtol,
            "atol": atol,
            "max_step": max_step,
            "negativity_tolerance_amount_mg": neg_tol,
            "ke_consistency_rtol": KE_RTOL,
            "ke_consistency_atol": KE_ATOL,
            "dosing_convention": "A_gut(0)=Dose (single instantaneous oral dose at t=0)",
            "bioavailability_convention": "F applied in absorption flux F*ka*A_gut; CL and V are systemic (not apparent)",
        },
    }
    return results


# -------------------------
# Plotting
# -------------------------
def plot_pkpd(results: Dict[str, np.ndarray], title_suffix: str = "") -> None:
    """
    Plot concentration-time and effect-time from simulation results dictionary.
    Does not re-run simulation; accepts the returned dict from simulate_pkpd.
    """
    t = results["time"]
    C = results["concentration"]
    E = results["effect"]
    units = results.get("units", {})
    time_unit = units.get("time", "h")
    conc_unit = units.get("concentration", "mg/L")
    eff_unit = units.get("effect", "units")

    fig, axes = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
    axes[0].plot(t, C, color="C0", lw=1.5)
    axes[0].set_ylabel(f"Concentration ({conc_unit})", fontsize=10)
    axes[0].set_title(f"Concentration vs Time {title_suffix}".strip())
    axes[0].grid(True)

    axes[1].plot(t, E, color="C1", lw=1.5)
    axes[1].set_xlabel(f"Time ({time_unit})", fontsize=10)
    axes[1].set_ylabel(f"Effect ({eff_unit})", fontsize=10)
    axes[1].set_title(f"Pharmacodynamic Effect vs Time {title_suffix}".strip())
    axes[1].grid(True)

    plt.tight_layout()
    plt.show()


# -------------------------
# Runnable demonstration
# -------------------------
if __name__ == "__main__":
    # Synthetic demonstration parameters (for demonstration only, not a real drug)
    Dose = 100.0  # mg
    F = 0.6  # fraction (dimensionless)
    ka = 1.0  # 1/h (absorption is relatively fast; t1/2,abs ~ 0.693 h)
    V = 20.0  # L
    CL = 1.0  # L/h -> ke = 0.05 1/h (t1/2,elim ~ 13.86 h)
    # PD parameters
    E0 = 0.0  # baseline effect units
    Emax = 100.0  # effect units
    EC50 = 2.0  # mg/L
    gamma = 1.5  # Hill coefficient (dimensionless)

    # Simulation time grid defaults (0..48 h, dt=0.05 h)
    t_start = 0.0
    t_end = 48.0
    dt = 0.05
    t_eval = np.arange(t_start, t_end + dt / 2.0, dt, dtype=float)

    # Run simulation
    results = simulate_pkpd(
        Dose=Dose,
        F=F,
        ka=ka,
        V=V,
        CL=CL,
        E0=E0,
        Emax=Emax,
        EC50=EC50,
        gamma=gamma,
        t_start=t_start,
        t_end=t_end,
        t_eval=t_eval,
    )

    # Validation checks (PK identity, PD behavior, state checks)
    ke_computed = results["ke"]
    # PK consistency check: ke = CL / V
    ke_expected = CL / V
    assert np.isclose(ke_computed, ke_expected, rtol=KE_RTOL, atol=KE_ATOL), "ke inconsistency."

    # PD checks: finite-concentration validation (not asymptotic)
    C_zero = 0.0
    C_half = EC50
    C_high = 1000.0 * EC50

    E_at_0 = sigmoid_emax(np.array([C_zero]), E0=E0, Emax=Emax, EC50=EC50, gamma=gamma)[0]
    E_at_half = sigmoid_emax(np.array([C_half]), E0=E0, Emax=Emax, EC50=EC50, gamma=gamma)[0]
    E_at_high = sigmoid_emax(np.array([C_high]), E0=E0, Emax=Emax, EC50=EC50, gamma=gamma)[0]

    # Baseline check
    assert np.allclose(E_at_0, E0, rtol=1e-12, atol=1e-12), "PD check failed at C=0."

    # Half-maximal effect check
    assert np.allclose(E_at_half, E0 + Emax / 2.0, rtol=1e-8, atol=1e-12), "PD check failed at C=EC50."

    # Finite high-concentration check: compare to exact finite analytical value, not asymptote
    ratio = C_high / EC50
    expected_high = E0 + Emax * ratio**gamma / (1.0 + ratio**gamma)
    assert np.allclose(E_at_high, expected_high, rtol=1e-12, atol=1e-12), \
        f"PD check failed at C=1000*EC50: computed {E_at_high:.8g}, expected {expected_high:.8g}."

    # Asymptotic behavior: verify finite effect < asymptote and residual is positive
    asymptotic_effect = E0 + Emax
    residual = asymptotic_effect - E_at_high
    assert residual > 0, f"Residual should be positive; got {residual:.3g}."
    expected_residual = Emax / (1.0 + ratio**gamma)
    assert np.allclose(residual, expected_residual, rtol=1e-12, atol=1e-12), \
        f"Asymptotic residual mismatch: computed {residual:.8g}, expected {expected_residual:.8g}."

    # State checks
    assert np.all(np.isfinite(results["A_gut"])) and np.all(np.isfinite(results["A_central"])), "Non-finite states."
    assert np.min(results["A_gut"]) >= -results["meta"]["negativity_tolerance_amount_mg"] - 1e-15
    assert np.min(results["A_central"]) >= -results["meta"]["negativity_tolerance_amount_mg"] - 1e-15
    assert np.all(results["concentration"] >= -1e-14)

    # Print concise diagnostics
    print("=" * 70)
    print("Simulation completed successfully.")
    print("=" * 70)
    print(f"ke (computed) = {ke_computed:.8g} 1/h, ke (CL/V) = {ke_expected:.8g} 1/h")
    print()
    print("PD Validation:")
    print(f"  E(0) = {E_at_0:.6g} (expected {E0})")
    print(f"  E(EC50) = {E_at_half:.6g} (expected {E0 + Emax/2})")
    print(f"  E(1000*EC50) = {E_at_high:.8g}")
    print(f"    Exact finite analytical = {expected_high:.8g}")
    print(f"    Asymptotic limit (E0 + Emax) = {asymptotic_effect:.8g}")
    print(f"    Residual from asymptote = {residual:.8g}")
    print()
    print("All validation checks passed.")
    print("=" * 70)

    # Plot results
    plot_pkpd(results, title_suffix="(synthetic demonstration)")