# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4qJmuhRdMDOCpYQZgzs34VwokEPIcou
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# App title
st.title("KHU-Circadian Rhythm Simulator")

# User inputs
M = st.number_input("MESOR (Midline Statistic Of Rhythm)", value=0.0)
A = st.number_input("Amplitude", value=1.0)
T = st.number_input("Period (hours)", value=24.0)
AP_hour = st.number_input("Acrophase (in hours)", value=0.0)
duration = st.slider("Simulation Duration (hours)", min_value=24, max_value=168, value=72)

# Convert acrophase from hours to radians
AP = (2 * np.pi * AP_hour) / T

# Create time array
x = np.linspace(0, duration, 500)

# Circadian rhythm model
C = M + A * np.cos((2 * np.pi * x / T) - AP)

# Plot
fig, ax = plt.subplots()
ax.plot(x, C)
ax.set_xlabel("Time (hours)")
ax.set_ylabel("Circadian Rhythm Value")
ax.set_title("KHU-Circadian Rhythm Simulation")
ax.grid(True)

# Display plot in Streamlit
st.pyplot(fig)