# -*- coding: utf-8 -*-
"""KHU-PKT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3K-ukZ1KXfRBsNS3j45GXYEW899H_dy
"""

# app.py

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint, simpson
import pandas as pd
from scipy.optimize import curve_fit
from scipy import stats
import warnings

# -----------------------------
# 공통 페이지 설정
# -----------------------------
st.set_page_config(page_title="KHU Pharmacokinetic Modeling Platform",
                   layout="wide", page_icon="💊")
st.title("💊 KHU Pharmacokinetic Modeling Platform")

st.sidebar.title("Modules")
module = st.sidebar.radio(
    "Select module",
    [
        "KHU-Circadian Rhythm",
        "KHU-PK",
        "KHU-PK/PD",
        "KHU-Transit Compartment",
        "KHU-PKMA",
    ]
)

# =============================
# 1) KHU-CR (Circadian Rhythm)
# =============================
def run_circadian():
    st.header("KHU-Circadian Rhythm Simulator")

    M = st.number_input("MESOR (Midline Statistic Of Rhythm)", value=0.0)
    A = st.number_input("Amplitude", value=1.0)
    T = st.number_input("Period (hours)", value=24.0)
    AP_hour = st.number_input("Acrophase (in hours)", value=0.0)
    duration = st.slider("Simulation Duration (hours)",
                         min_value=24, max_value=168, value=72)

    # radian 변환
    AP = (2 * np.pi * AP_hour) / T

    # time axis
    x = np.linspace(0, duration, 500)

    # cosinor model
    C = M + A * np.cos((2 * np.pi * x / T) - AP)

    fig, ax = plt.subplots()
    ax.plot(x, C)
    ax.set_xlabel("Time (hours)")
    ax.set_ylabel("Circadian Rhythm Value")
    ax.set_title("Circadian Rhythm Simulation")
    ax.grid(True)
    st.pyplot(fig)

# =============================
# 2) KHU-PK
# =============================
def run_pk():
    st.header("KHU-PK Simulator")

    # ---- 공통 함수 ----
    def create_time_vector(duration, dt=0.1):
        return np.arange(0, duration + dt, dt)

    def simulate_ode(time, tau, n_doses, ode_func, y0, params, repeat=False):
        full_result = np.zeros((len(time), len(y0)))
        y = y0.copy()

        if repeat:
            for i in range(n_doses):
                t_start = i * tau
                t_end = time[-1] if i == n_doses - 1 else (i + 1) * tau
                if i == n_doses - 1:
                    mask = (time >= t_start) & (time <= t_end)
                else:
                    mask = (time >= t_start) & (time < t_end)
                t_segment = time[mask] - t_start
                if i > 0:
                    y[0] += params['dose']
                result = odeint(ode_func, y, t_segment, args=(params,))
                full_result[mask] = result
                y = result[-1]
        else:
            result = odeint(ode_func, y0, time, args=(params,))
            full_result = result

        return full_result

    # ---- 모델 정의 ----
    def one_compartment_iv_ode(y, t, p):
        A = y[0]
        return [-p['kel'] * A]

    def one_compartment_po_ode(y, t, p):
        Ag, A = y
        dAg_dt = -p['ka'] * Ag
        dA_dt = p['ka'] * Ag - p['kel'] * A
        return [dAg_dt, dA_dt]

    def one_compartment_infusion_ode(y, t, p):
        A = y[0]
        k0 = p['dose'] / p['infusion_time'] if t <= p['infusion_time'] else 0
        return [k0 - p['kel'] * A]

    def two_compartment_iv_ode(y, t, p):
        A1, A2 = y
        dA1 = -p['k10'] * A1 - p['k12'] * A1 + p['k21'] * A2
        dA2 = p['k12'] * A1 - p['k21'] * A2
        return [dA1, dA2]

    def two_compartment_po_ode(y, t, p):
        Ag, A1, A2 = y
        dAg = -p['ka'] * Ag
        dA1 = p['ka'] * Ag - p['k10'] * A1 - p['k12'] * A1 + p['k21'] * A2
        dA2 = p['k12'] * A1 - p['k21'] * A2
        return [dAg, dA1, dA2]

    def two_compartment_infusion_ode(y, t, p):
        A1, A2 = y
        k0 = p['dose'] / p['infusion_time'] if t <= p['infusion_time'] else 0
        dA1 = k0 - p['k10'] * A1 - p['k12'] * A1 + p['k21'] * A2
        dA2 = p['k12'] * A1 - p['k21'] * A2
        return [dA1, dA2]

    # ---- UI ----
    model_type = st.selectbox(
        "Select a model",
        [
            "1 Compartment IV",
            "1 Compartment IV (Multiple Dosing)",
            "1 Compartment PO",
            "1 Compartment PO (Multiple Dosing)",
            "1 Compartment Infusion",
            "2 Compartment IV",
            "2 Compartment IV (Multiple Dosing)",
            "2 Compartment PO",
            "2 Compartment PO (Multiple Dosing)",
            "2 Compartment Infusion"
        ]
    )

    repeat = "Multiple Dosing" in model_type

    dose = st.number_input("Dose per administration (mg)", value=500.0)
    tau = st.number_input("Dosing interval τ (hr)", value=8.0) if repeat else None
    n_doses = st.number_input("Number of doses", value=10, step=1) if repeat else 1

    # 파라미터 입력
    if model_type.startswith("1 Compartment IV"):
        Vd = st.number_input("Volume of distribution (Vd, L)", value=20.0)
        kel = st.number_input("Elimination rate constant (kel, 1/hr)", value=0.2)
        params = {'dose': dose, 'kel': kel}
    elif model_type.startswith("1 Compartment PO"):
        Vd = st.number_input("Volume of distribution (Vd, L)", value=20.0)
        ka = st.number_input("Absorption rate constant (ka, 1/hr)", value=1.0)
        kel = st.number_input("Elimination rate constant (kel, 1/hr)", value=0.2)
        params = {'dose': dose, 'ka': ka, 'kel': kel}
    elif model_type.startswith("2 Compartment IV"):
        V1 = st.number_input("Central volume (V1, L)", value=15.0)
        k10 = st.number_input("k10 (1/hr)", value=0.15)
        k12 = st.number_input("k12 (1/hr)", value=0.1)
        k21 = st.number_input("k21 (1/hr)", value=0.05)
        params = {'dose': dose, 'k10': k10, 'k12': k12, 'k21': k21}
    elif model_type.startswith("2 Compartment PO"):
        V1 = st.number_input("Central volume (V1, L)", value=15.0)
        ka = st.number_input("Absorption rate constant (ka, 1/hr)", value=1.2)
        k10 = st.number_input("k10 (1/hr)", value=0.15)
        k12 = st.number_input("k12 (1/hr)", value=0.1)
        k21 = st.number_input("k21 (1/hr)", value=0.05)
        params = {'dose': dose, 'ka': ka, 'k10': k10, 'k12': k12, 'k21': k21}
    elif model_type == "1 Compartment Infusion":
        Vd = st.number_input("Volume of distribution (Vd, L)", value=20.0)
        kel = st.number_input("Elimination rate constant (kel, 1/hr)", value=0.2)
        infusion_time = st.number_input("Infusion duration (hr)", value=2.0)
        params = {'dose': dose, 'kel': kel, 'infusion_time': infusion_time}
    elif model_type == "2 Compartment Infusion":
        V1 = st.number_input("Central volume (V1, L)", value=15.0)
        k10 = st.number_input("k10 (1/hr)", value=0.15)
        k12 = st.number_input("k12 (1/hr)", value=0.1)
        k21 = st.number_input("k21 (1/hr)", value=0.05)
        infusion_time = st.number_input("Infusion duration (hr)", value=2.0)
        params = {'dose': dose, 'k10': k10, 'k12': k12, 'k21': k21,
                  'infusion_time': infusion_time}

    # 시뮬레이션 기간
    if repeat:
        metrics_end = tau * n_doses
        extension = tau
        duration = metrics_end + extension
    else:
        duration = 24

    time = create_time_vector(duration)

    # ODE 실행
    if model_type.startswith("1 Compartment IV"):
        y0 = [dose]
        result = simulate_ode(time, tau, int(n_doses),
                              one_compartment_iv_ode, y0, params, repeat)
    elif model_type.startswith("1 Compartment PO"):
        y0 = [dose, 0]
        result = simulate_ode(time, tau, int(n_doses),
                              one_compartment_po_ode, y0, params, repeat)
    elif model_type == "1 Compartment Infusion":
        y0 = [0]
        result = simulate_ode(time, tau, int(n_doses),
                              one_compartment_infusion_ode, y0, params, repeat)
    elif model_type.startswith("2 Compartment IV"):
        y0 = [dose, 0]
        result = simulate_ode(time, tau, int(n_doses),
                              two_compartment_iv_ode, y0, params, repeat)
    elif model_type.startswith("2 Compartment PO"):
        y0 = [dose, 0, 0]
        result = simulate_ode(time, tau, int(n_doses),
                              two_compartment_po_ode, y0, params, repeat)
    elif model_type == "2 Compartment Infusion":
        y0 = [0, 0]
        result = simulate_ode(time, tau, int(n_doses),
                              two_compartment_infusion_ode, y0, params, repeat)

    # compartment 선택
    compartment_names = [f"Compartment {i+1}" for i in range(result.shape[1])]
    selected_compartments = st.multiselect(
        "Select compartments to display",
        compartment_names,
        default=compartment_names
    )

    if st.button("Plot Graph"):
        fig, ax = plt.subplots()
        # 볼륨 값 (Vd 또는 V1)
        vol = locals().get('Vd', locals().get('V1', 1.0))

        for i, name in enumerate(compartment_names):
            if name in selected_compartments:
                ax.plot(time, result[:, i] / vol, label=name)

        ax.set_xlabel('Time (hr)')
        ax.set_ylabel('Concentration (mg/L)')
        ax.set_title('Concentration-Time Profile')
        ax.legend()
        st.pyplot(fig)

        # 중심 compartment 농도 선택
        if 'Vd' in locals():
            conc = result[:, 1] / Vd if model_type.startswith("1 Compartment PO") \
                   else result[:, 0] / Vd
        else:
            conc = result[:, 0] / V1

        AUC = simpson(conc, time)

        # 지연투여/반복투여 vs 단회투여
        if repeat:
            idx_prev = np.where((time >= metrics_end - 2*tau) &
                                (time < metrics_end - tau))[0]
            idx_last = np.where((time >= metrics_end - tau) &
                                (time < metrics_end))[0]
            conc_prev = conc[idx_prev]
            conc_last = conc[idx_last]
            Cmax_prev = np.max(conc_prev)
            Cmax_last = np.max(conc_last)
            Cmin_prev = np.min(conc_prev)
            Cmin_last = np.min(conc_last)
            ss_reached = (abs(Cmax_last - Cmax_prev) / Cmax_last < 0.05) and \
                         (abs(Cmin_last - Cmin_prev) / Cmin_last < 0.05)
            ss_text = '🟢 Steady-state reached' if ss_reached else '🔴 Not at steady-state'
            Css_max = Cmax_last
            Css_min = Cmin_last
            Css_avg = simpson(conc_last, time[idx_last]) / tau

            st.markdown(f"**Steady-state average concentration (Cavg):** {Css_avg:.4f} mg/L")
            st.markdown(f"**Steady-state maximum concentration (Cmax):** {Css_max:.4f} mg/L")
            st.markdown(f"**Steady-state minimum concentration (Cmin):** {Css_min:.4f} mg/L")
            st.markdown(f"**Total AUC (0–{duration:.1f} hr):** {AUC:.2f} mg·hr/L")
            st.markdown(f"**Steady-state status:** {ss_text}")
        else:
            Cmax = np.max(conc)
            Tmax = time[np.argmax(conc)]
            st.markdown(f"**Cmax:** {Cmax:.2f} mg/L")
            st.markdown(f"**Tmax:** {Tmax:.2f} hr")
            st.markdown(f"**AUC (0–{duration:.1f} hr):** {AUC:.2f} mg·hr/L")

# =============================
# 3) KHU-PK/PD
# =============================
def run_pkpd():
    st.header("KHU-PK/PD Simulator")

    model = st.selectbox("Select a model", [
        "Emax Model",
        "1 Compartment IV & Emax model",
        "1 Compartment Infusion & Emax model",
        "1 Compartment PO & Emax model",
        "2 Compartment IV & Emax model",
        "2 Compartment Infusion & Emax model",
        "2 Compartment PO & Emax model"
    ])

    t = np.linspace(0, 48, 500)

    st.subheader("🧪 PD Parameters (Emax Model)")
    col1, col2 = st.columns(2)
    with col1:
        Emax = st.number_input("Emax", value=1.0, step=0.1)
    with col2:
        EC50 = st.number_input("EC50", value=2.0, step=0.1)

    def compute_emax(C):
        return Emax * C / (EC50 + C)

    def plot_concentration_and_effect(t, C, E):
        fig, ax1 = plt.subplots()
        ax1.plot(t, C, label='Concentration')
        ax1.set_xlabel('Time (hr)')
        ax1.set_ylabel('Concentration (mg/L)')
        ax2 = ax1.twinx()
        ax2.plot(t, E, linestyle='--', label='Effect')
        ax2.set_ylabel('Effect')
        fig.tight_layout()
        st.pyplot(fig)

    if model == "Emax Model":
        C = np.linspace(0, 10, 200)
        E = compute_emax(C)
        fig, ax = plt.subplots()
        ax.plot(C, E, label="Effect vs Concentration")
        ax.axhline(Emax, linestyle='--', label='Emax')
        ax.axvline(EC50, linestyle='--', label='EC50')
        ax.set_xlabel('Concentration (mg/L)')
        ax.set_ylabel('Effect')
        ax.legend()
        st.pyplot(fig)

    elif model == "1 Compartment IV & Emax model":
        st.subheader("PK Parameters")
        col1, col2 = st.columns(2)
        with col1:
            dose = st.number_input("IV Dose (mg)", value=100.0)
            ke = st.number_input("ke (/hr)", value=0.1, step=0.01)
        with col2:
            Vd = st.number_input("Vd (L)", value=10.0)

        def model_iv(y, t, ke):
            A = y[0]
            dAdt = -ke * A
            return [dAdt]

        y0 = [dose]
        A = odeint(model_iv, y0, t, args=(ke,))
        C = A[:, 0] / Vd
        E = compute_emax(C)
        plot_concentration_and_effect(t, C, E)

    elif model == "1 Compartment Infusion & Emax model":
        st.subheader("PK Parameters")
        col1, col2 = st.columns(2)
        with col1:
            R = st.number_input("Infusion Rate (mg/hr)", value=10.0)
            duration = st.number_input("Infusion Duration (hr)",
                                       value=2.0, step=0.1)
        with col2:
            ke = st.number_input("ke (/hr)", value=0.1, step=0.01)
            Vd = st.number_input("Vd (L)", value=10.0)

        def model_infusion(y, t, R, ke, duration):
            A = y[0]
            infusion = R if t <= duration else 0
            dAdt = infusion - ke * A
            return [dAdt]

        y0 = [0.0]
        A = odeint(model_infusion, y0, t, args=(R, ke, duration))
        C = A[:, 0] / Vd
        E = compute_emax(C)
        plot_concentration_and_effect(t, C, E)

    elif model == "1 Compartment PO & Emax model":
        st.subheader("PK Parameters")
        col1, col2 = st.columns(2)
        with col1:
            dose = st.number_input("Oral Dose (mg)", value=100.0)
            ka = st.number_input("ka (/hr)", value=1.0, step=0.1)
        with col2:
            ke = st.number_input("ke (/hr)", value=0.1, step=0.01)
            Vd = st.number_input("Vd (L)", value=10.0)

        def model_po(y, t, ka, ke, Vd):
            A, Cc = y
            dAdt = -ka * A
            dCdt = (ka * A / Vd) - ke * Cc
            return [dAdt, dCdt]

        y0 = [dose, 0.0]
        result = odeint(model_po, y0, t, args=(ka, ke, Vd))
        C = result[:, 1]
        E = compute_emax(C)
        plot_concentration_and_effect(t, C, E)

    elif model == "2 Compartment IV & Emax model":
        st.subheader("PK Parameters")
        col1, col2 = st.columns(2)
        with col1:
            dose = st.number_input("IV Dose (mg)", value=100.0)
            k10 = st.number_input("k10 (/hr)", value=0.1, step=0.01)
            k12 = st.number_input("k12 (/hr)", value=0.05, step=0.01)
        with col2:
            k21 = st.number_input("k21 (/hr)", value=0.05, step=0.01)
            V1 = st.number_input("Central Volume V1 (L)", value=10.0)

        def model_2c_iv(y, t, k10, k12, k21):
            A1, A2 = y
            dA1dt = -k10*A1 - k12*A1 + k21*A2
            dA2dt = k12*A1 - k21*A2
            return [dA1dt, dA2dt]

        y0 = [dose, 0.0]
        result = odeint(model_2c_iv, y0, t, args=(k10, k12, k21))
        C = result[:, 0] / V1
        E = compute_emax(C)
        plot_concentration_and_effect(t, C, E)

    elif model == "2 Compartment Infusion & Emax model":
        st.subheader("PK Parameters")
        col1, col2 = st.columns(2)
        with col1:
            R = st.number_input("Infusion Rate (mg/hr)", value=10.0)
            duration = st.number_input("Infusion Duration (hr)",
                                       value=2.0, step=0.1)
        with col2:
            k10 = st.number_input("k10 (/hr)", value=0.1, step=0.01)
            k12 = st.number_input("k12 (/hr)", value=0.05, step=0.01)
            k21 = st.number_input("k21 (/hr)", value=0.05, step=0.01)
            V1 = st.number_input("Central Volume V1 (L)", value=10.0)

        def model_2c_infusion(y, t, k10, k12, k21, R, duration):
            A1, A2 = y
            infusion = R if t <= duration else 0
            dA1dt = infusion - k10*A1 - k12*A1 + k21*A2
            dA2dt = k12*A1 - k21*A2
            return [dA1dt, dA2dt]

        y0 = [0.0, 0.0]
        result = odeint(model_2c_infusion, y0, t,
                        args=(k10, k12, k21, R, duration))
        C = result[:, 0] / V1
        E = compute_emax(C)
        plot_concentration_and_effect(t, C, E)

    elif model == "2 Compartment PO & Emax model":
        st.subheader("PK Parameters")
        col1, col2 = st.columns(2)
        with col1:
            dose = st.number_input("Oral Dose (mg)", value=100.0)
            ka = st.number_input("ka (/hr)", value=1.0, step=0.1)
            k10 = st.number_input("k10 (/hr)", value=0.1, step=0.01)
        with col2:
            k12 = st.number_input("k12 (/hr)", value=0.05, step=0.01)
            k21 = st.number_input("k21 (/hr)", value=0.05, step=0.01)
            V1 = st.number_input("Central Volume V1 (L)", value=10.0)

        def model_2c_po(y, t, ka, k10, k12, k21):
            Ag, A1, A2 = y
            dAgdt = -ka * Ag
            dA1dt = ka * Ag - k10*A1 - k12*A1 + k21*A2
            dA2dt = k12*A1 - k21*A2
            return [dAgdt, dA1dt, dA2dt]

        y0 = [dose, 0.0, 0.0]
        result = odeint(model_2c_po, y0, t, args=(ka, k10, k12, k21))
        C = result[:, 1] / V1
        E = compute_emax(C)
        plot_concentration_and_effect(t, C, E)

# =============================
# 4) KHU-Transit Compartment
# =============================
def run_transit():
    st.header("KHU-Transit Compartment Model Simulator")

    def transit_model(y, t, n, k_tr):
        dydt = np.zeros(n + 1)
        dydt[0] = -k_tr * y[0]
        for i in range(1, n):
            dydt[i] = k_tr * (y[i - 1] - y[i])
        dydt[n] = k_tr * y[n - 1]
        return dydt

    def simulate_transit(n, k_tr, dose, t_end=24, num_points=500):
        y0 = np.zeros(n + 1)
        y0[0] = dose
        t = np.linspace(0, t_end, num_points)
        sol = odeint(transit_model, y0, t, args=(n, k_tr))
        return t, sol

    n = st.number_input("Number of Transit Compartments",
                        min_value=1, max_value=20, value=5, step=1)
    k_tr = st.number_input("Transit Rate (k_tr, 1/hr)",
                           min_value=0.01, value=1.0, step=0.1)
    dose = st.number_input("Initial Dose",
                           min_value=0.0, value=100.0, step=10.0)
    t_end = st.number_input("Simulation Time (hr)",
                            min_value=1, value=24, step=1)

    available_compartments = [f"Compartment {i}" for i in range(int(n))] + ["Absorption"]
    selected_compartments = st.multiselect(
        "Select Compartments to Display",
        available_compartments,
        default=["Absorption"]
    )

    if st.button("Run Simulation"):
        t, sol = simulate_transit(int(n), k_tr, dose, t_end)
        comp_to_idx = {f"Compartment {i}": i for i in range(int(n))}
        comp_to_idx["Absorption"] = int(n)

        fig, ax = plt.subplots()
        for comp in selected_compartments:
            idx = comp_to_idx[comp]
            ax.plot(t, sol[:, idx], label=comp)

        ax.set_xlabel("Time (hr)")
        ax.set_ylabel("Amount")
        ax.set_title("Transit Compartment Concentration")
        ax.legend()
        st.pyplot(fig)

# =============================
# 5) KHU-PKMA (NCA + 모델 적합)
# =============================
def run_pkma():
    st.header("KHU-PKMA : Pharmacokinetic Model Assistant")

    # ---- 데이터 입력 ----
    st.sidebar.header("📂 Data Input")
    example = st.sidebar.checkbox("Use Example Data", value=True)

    if example:
        time = np.array([0.5, 1, 2, 4, 6, 8, 12], dtype=float)
        conc = np.array([15.3, 13.1, 10.0, 6.1, 4.2, 2.9, 1.3], dtype=float)
        df = pd.DataFrame({'time': time, 'conc': conc})
    else:
        uploaded_file = st.sidebar.file_uploader(
            "Upload CSV (must include 'time','conc' columns)", type="csv"
        )

        with st.sidebar.expander("📝 View CSV Format Example"):
            st.markdown("""
            The uploaded CSV file must follow this format:

            | time | conc |
            |------|------|
            | 0.5  | 15.3 |
            | 1.0  | 13.1 |
            | 2.0  | 10.0 |
            | ...  | ...  |

            - `time`: Time (hours, h)
            - `conc`: Drug concentration (e.g., mg/L)
            - Column names must be exactly `time`, `conc`
            - CSV must be comma-delimited
            """)

        if uploaded_file:
            df = pd.read_csv(uploaded_file)
            if not set(["time", "conc"]).issubset(df.columns):
                st.error("CSV must have columns named exactly 'time' and 'conc'.")
                return
            df = df.dropna(subset=["time", "conc"]).copy()
            df["time"] = pd.to_numeric(df["time"], errors="coerce")
            df["conc"] = pd.to_numeric(df["conc"], errors="coerce")
            df = df.dropna(subset=["time", "conc"]).sort_values("time")
            if len(df) < 3:
                st.error("Need at least 3 rows of (time, conc) data.")
                return
        else:
            st.warning("Please upload a CSV file or select example data.")
            return

    # ---- 분석 종류 ----
    analysis_type = st.sidebar.radio(
        "🔍 Select Analysis Type",
        ["NCA Analysis", "Compartment Model Analysis"]
    )

    # ---- 공통 모델 함수들 ----
    def simulate_ode_iv(t, dose, k10, V):
        def ode_iv(y, tt):
            A = y[0]
            return [-k10 * A]
        y0 = [dose]
        result = odeint(ode_iv, y0, t)
        return result[:, 0] / V

    def simulate_ode_po(t, dose, ka, k, V):
        def ode_po(y, tt):
            A_gut, A_c = y
            return [-ka * A_gut, ka * A_gut - k * A_c]
        y0 = [dose, 0.0]
        result = odeint(ode_po, y0, t)
        return result[:, 1] / V

    def simulate_ode_two_comp_iv(t, dose, k10, k12, k21, V1):
        def model(y, tt):
            A1, A2 = y
            dA1dt = -k10*A1 - k12*A1 + k21*A2
            dA2dt = k12*A1 - k21*A2
            return [dA1dt, dA2dt]
        y0 = [dose, 0.0]
        result = odeint(model, y0, t)
        return result[:, 0] / V1

    def simulate_ode_two_comp_po(t, dose, ka, k10, k12, k21, V1):
        def model(y, tt):
            A_gut, A1, A2 = y
            dA_gut_dt = -ka * A_gut
            dA1dt = ka*A_gut - k10*A1 - k12*A1 + k21*A2
            dA2dt = k12*A1 - k21*A2
            return [dA_gut_dt, dA1dt, dA2dt]
        y0 = [dose, 0.0, 0.0]
        result = odeint(model, y0, t)
        return result[:, 1] / V1

    def perform_nca(df, terminal_indices=None):
        t = df['time'].values.astype(float)
        c = df['conc'].values.astype(float)

        # AUClast
        auc = np.trapz(c, t)

        # terminal phase 선택
        if terminal_indices is not None and len(terminal_indices) >= 2:
            t_term = t[terminal_indices]
            c_term = c[terminal_indices]
        else:
            mask_pos = c > 0
            t_pos = t[mask_pos]
            c_pos = c[mask_pos]
            if len(t_pos) < 3:
                t_term, c_term = t_pos[-2:], c_pos[-2:]
            else:
                t_term, c_term = t_pos[-3:], c_pos[-3:]

        if len(t_term) < 2 or np.any(c_term <= 0):
            kel = np.nan
            t12 = np.nan
        else:
            slope, _, _, _, _ = stats.linregress(t_term, np.log(c_term))
            kel = -slope
            t12 = np.log(2) / kel if kel > 0 else np.nan

        dose = st.sidebar.number_input("Dose (mg)", value=100.0)
        cl = dose / auc if auc > 0 else np.nan
        return auc, kel, t12, cl

    def show_model_info(model):
        st.markdown("### 📘 Model Description")
        if model == "1 Compartment IV":
            st.latex(r"\frac{dA}{dt} = -k \cdot A")
            st.latex(r"C(t) = \frac{A(t)}{V}")
        elif model == "1 Compartment PO":
            st.latex(r"""
            \begin{cases}
            \frac{dA_g}{dt} = -k_a A_g \\
            \frac{dA_c}{dt} = k_a A_g - k A_c
            \end{cases}
            """)
            st.latex(r"C(t) = \frac{A_c(t)}{V}")
        elif model == "2 Compartment IV":
            st.latex(r"""
            \begin{cases}
            \frac{dA_1}{dt} = -k_{10}A_1 - k_{12}A_1 + k_{21}A_2 \\
            \frac{dA_2}{dt} = k_{12}A_1 - k_{21}A_2
            \end{cases}
            """)
            st.latex(r"C(t) = \frac{A_1(t)}{V_1}")
        elif model == "2 Compartment PO":
            st.latex(r"""
            \begin{cases}
            \frac{dA_g}{dt} = -k_a A_g \\
            \frac{dA_1}{dt} = k_a A_g - k_{10}A_1 - k_{12}A_1 + k_{21}A_2 \\
            \frac{dA_2}{dt} = k_{12}A_1 - k_{21}A_2
            \end{cases}
            """)
            st.latex(r"C(t) = \frac{A_1(t)}{V_1}")

    # ---- NCA ----
    if analysis_type == "NCA Analysis":
        st.subheader("📐 NCA Analysis")

        auto_mode = st.radio("Terminal Phase Selection", ["Automatic", "Manual"])
        if auto_mode == "Manual":
            selected_points = st.multiselect(
                "Select terminal phase times",
                df['time'].tolist(),
                default=df['time'].tolist()[-3:]
            )
            terminal_idx = df.index[df['time'].isin(selected_points)].tolist()
        else:
            terminal_idx = None

        auc, kel, t12, cl = perform_nca(df, terminal_idx)

        st.markdown(
            f"**AUClast:** {auc:.2f} (h·mg/L)  \n"
            f"**λz (kel):** {kel if np.isfinite(kel) else float('nan'):.4f} h⁻¹  \n"
            f"**t1/2:** {t12 if np.isfinite(t12) else float('nan'):.2f} h  \n"
            f"**CL:** {cl if np.isfinite(cl) else float('nan'):.2f} L/h"
        )

        st.subheader("📈 Concentration-Time Curve")
        fig, ax = plt.subplots()
        ax.plot(df['time'], df['conc'], 'o-', label='Observed')
        ax.set_xlabel("Time (h)")
        ax.set_ylabel("Concentration (mg/L)")
        ax.legend()
        st.pyplot(fig)

    # ---- Compartment model 분석 ----
    elif analysis_type == "Compartment Model Analysis":
        st.subheader("🧮 Compartment Model Analysis")

        model = st.sidebar.selectbox(
            "Select Model",
            ["1 Compartment IV", "1 Compartment PO", "2 Compartment IV", "2 Compartment PO"]
        )

        show_model_info(model)

        dose = st.sidebar.number_input("Dose (mg)", value=100.0)
        use_log = st.sidebar.checkbox("Plot in Log Scale", value=False)

        t_vals = df['time'].values.astype(float)
        y_vals = df['conc'].values.astype(float)

        if np.any(~np.isfinite(t_vals)) or np.any(~np.isfinite(y_vals)):
            st.error("Non-finite values found in time/conc.")
            return

        def fit_model(model_name, t, y, dose):
            bounds = (0, np.inf)

            if model_name == "1 Compartment IV":
                def model_func(tt, k10, V):
                    return simulate_ode_iv(tt, dose, k10, V)
                p0 = [0.2, max(1.0, dose / max(y.max(), 1e-6))]
                param_names = ["k10", "V"]

            elif model_name == "1 Compartment PO":
                def model_func(tt, ka, k, V):
                    return simulate_ode_po(tt, dose, ka, k, V)
                p0 = [1.0, 0.2, max(1.0, dose / max(y.max(), 1e-6))]
                param_names = ["ka", "k", "V"]

            elif model_name == "2 Compartment IV":
                def model_func(tt, k10, k12, k21, V1):
                    return simulate_ode_two_comp_iv(tt, dose, k10, k12, k21, V1)
                p0 = [0.2, 0.1, 0.1, max(1.0, dose / max(y.max(), 1e-6))]
                param_names = ["k10", "k12", "k21", "V1"]

            elif model_name == "2 Compartment PO":
                def model_func(tt, ka, k10, k12, k21, V1):
                    return simulate_ode_two_comp_po(tt, dose, ka, k10, k12, k21, V1)
                p0 = [1.2, 0.2, 0.1, 0.1, max(1.0, dose / max(y.max(), 1e-6))]
                param_names = ["ka", "k10", "k12", "k21", "V1"]

            else:
                raise ValueError("Unknown model")

            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                popt, _ = curve_fit(
                    model_func, t, y, p0=p0,
                    bounds=bounds, maxfev=20000
                )

            pred = model_func(t, *popt)
            params = dict(zip(param_names, popt))
            return pred, popt, params

        try:
            pred, popt, params = fit_model(model, t_vals, y_vals, dose)
        except Exception as e:
            st.error(f"❌ curve_fit failed: {e}")
            st.info("Tips: Try different model, adjust Dose, or provide more data points.")
            return

        residuals = y_vals - pred
        ss_res = float(np.sum(residuals ** 2))
        n = len(y_vals)
        k_params = len(popt)
        aic = n * np.log(ss_res / n) + 2 * k_params if ss_res > 0 else np.nan
        bic = n * np.log(ss_res / n) + k_params * np.log(n) if ss_res > 0 else np.nan

        col1, col2 = st.columns(2)
        with col1:
            st.subheader("📊 Observed vs Predicted")
            fig, ax = plt.subplots()
            ax.plot(t_vals, y_vals, 'o', label='Observed')
            ax.plot(t_vals, pred, '-', label='Predicted')
            ax.set_xlabel("Time (h)")
            ax.set_ylabel("Concentration (mg/L)")
            if use_log:
                ymin = max(min(y_vals.min(), pred.min()), 1e-6)
                ax.set_ylim(bottom=ymin)
                ax.set_yscale("log")
            ax.legend()
            st.pyplot(fig)

        with col2:
            st.subheader("🧮 Estimated Parameters")
            param_units = {
                "k10": "h⁻¹", "ka": "h⁻¹", "k": "h⁻¹",
                "k12": "h⁻¹", "k21": "h⁻¹",
                "V": "L", "V1": "L",
            }
            for kname, val in params.items():
                unit = param_units.get(kname, "")
                st.write(f"**{kname} ({unit})**: {val:.4f}")
            st.write(f"**AIC**: {aic:.2f}")
            st.write(f"**BIC**: {bic:.2f}")

        st.subheader("📉 Residual Analysis")
        fig2, ax2 = plt.subplots(1, 2, figsize=(10, 4))
        ax2[0].hist(residuals, bins=10)
        ax2[0].set_title("Residual Histogram")
        ax2[1].scatter(pred, residuals)
        ax2[1].axhline(0, linestyle='--')
        ax2[1].set_title("Residuals vs Fitted")
        ax2[1].set_xlabel("Predicted")
        ax2[1].set_ylabel("Residuals")
        st.pyplot(fig2)

        # 다운로드
        st.subheader("📥 Download Results")
        df_out = df.copy()
        df_out['Predicted'] = pred
        df_out['Residuals'] = residuals
        csv = df_out.to_csv(index=False)
        st.download_button(
            "📄 Download Results as CSV",
            csv, "pk_result.csv", "text/csv"
        )

# =============================
# 모듈 분기
# =============================
if module == "KHU-Circadian Rhythm":
    run_circadian()
elif module == "KHU-PK":
    run_pk()
elif module == "KHU-PK/PD":
    run_pkpd()
elif module == "KHU-Transit Compartment":
    run_transit()
elif module == "KHU-PKMA":
    run_pkma()