# -*- coding: utf-8 -*-
"""testfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139eYdkEvy89_MCzSWPBANReVxl3NebM_
"""

# -*- coding: utf-8 -*-
"""KHU-PKMA Streamlit App
NCA는 그대로, 컴파트먼트 분석은 전부 ODE 형태 + PKSolver 스타일 피팅
"""

# 📦 Pharmacokinetics Integrated Analysis App
import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import curve_fit
from scipy.integrate import odeint
from scipy import stats
import warnings

# ----------------------------- #
# Streamlit page config
# ----------------------------- #
st.set_page_config(layout="wide")
st.title("💊 KHU-PKMA")
st.caption("Pharmacokinetic Model Assistant")

# ----------------------------- #
# 📁 Data Input
# ----------------------------- #
st.sidebar.header("📂 Data Input")
example = st.sidebar.checkbox("Use Example Data", value=True)

if example:
    time = np.array([0.5, 1, 2, 4, 6, 8, 12], dtype=float)
    conc = np.array([15.3, 13.1, 10.0, 6.1, 4.2, 2.9, 1.3], dtype=float)
    df = pd.DataFrame({'time': time, 'conc': conc})
else:
    uploaded_file = st.sidebar.file_uploader(
        "Upload CSV (must include 'time','conc' columns)", type="csv"
    )

    with st.sidebar.expander("📝 View CSV Format Example"):
        st.markdown("""
        The uploaded CSV file must follow this format:

        | time | conc |
        |------|------|
        | 0.5  | 15.3 |
        | 1.0  | 13.1 |
        | 2.0  | 10.0 |
        | ...  | ...  |

        - `time`: Time (hours, h)
        - `conc`: Drug concentration (e.g., mg/L)
        - Column names must be exactly `time`, `conc`
        - CSV must be comma-delimited
        """)

    if uploaded_file:
        df = pd.read_csv(uploaded_file)
        # Basic sanitation
        if not set(["time", "conc"]).issubset(df.columns):
            st.error("CSV must have columns named exactly 'time' and 'conc'.")
            st.stop()
        df = df.dropna(subset=["time", "conc"]).copy()
        df["time"] = pd.to_numeric(df["time"], errors="coerce")
        df["conc"] = pd.to_numeric(df["conc"], errors="coerce")
        df = df.dropna(subset=["time", "conc"]).sort_values("time")
        if len(df) < 3:
            st.error("Need at least 3 rows of (time, conc) data.")
            st.stop()
    else:
        st.warning("Please upload a CSV file or select example data.")
        st.stop()

# ----------------------------- #
# 🧭 Select Analysis Type
# ----------------------------- #
analysis_type = st.sidebar.radio(
    "🔍 Select Analysis Type", ["NCA Analysis", "Compartment Model Analysis"]
)

# ----------------------------- #
# ⚙️ 공통 모델 함수들 (전부 ODE 기반)
# ----------------------------- #

def simulate_ode_iv(t, dose, k10, V):
    """1 Compartment IV bolus ODE: dA/dt = -k10*A, C = A/V"""
    def ode_iv(A, tt):
        return -k10 * A
    y0 = [dose]
    # t은 증가 순서라고 가정
    result = odeint(ode_iv, y0, t)
    return result[:, 0] / V

def simulate_ode_po(t, dose, ka, k, V):
    """1 Compartment PO: A_gut, A_central"""
    def ode_po(y, tt):
        A_gut, A_c = y
        dA_gut = -ka * A_gut
        dA_c = ka * A_gut - k * A_c
        return [dA_gut, dA_c]
    y0 = [dose, 0.0]
    result = odeint(ode_po, y0, t)
    return result[:, 1] / V

def simulate_ode_two_comp_iv(t, dose, k10, k12, k21, V1):
    """2 Compartment IV: A1, A2"""
    def model(y, tt):
        A1, A2 = y
        dA1dt = -k10 * A1 - k12 * A1 + k21 * A2
        dA2dt = k12 * A1 - k21 * A2
        return [dA1dt, dA2dt]
    y0 = [dose, 0.0]
    result = odeint(model, y0, t)
    return result[:, 0] / V1

def simulate_ode_two_comp_po(t, dose, ka, k10, k12, k21, V1):
    """2 Compartment PO: A_gut, A1, A2"""
    def model(y, tt):
        A_gut, A1, A2 = y
        dA_gut = -ka * A_gut
        dA1dt = ka * A_gut - k10 * A1 - k12 * A1 + k21 * A2
        dA2dt = k12 * A1 - k21 * A2
        return [dA_gut, dA1dt, dA2dt]
    y0 = [dose, 0.0, 0.0]
    result = odeint(model, y0, t)
    return result[:, 1] / V1

# ----------------------------- #
# NCA (원래대로 유지)
# ----------------------------- #
def perform_nca(df, terminal_indices=None):
    t = df['time'].values.astype(float)
    c = df['conc'].values.astype(float)

    # AUClast
    auc = np.trapz(c, t)

    # terminal 구간 선택
    if terminal_indices is not None and len(terminal_indices) >= 2:
        t_term = t[terminal_indices]
        c_term = c[terminal_indices]
    else:
        mask_pos = c > 0
        t_pos = t[mask_pos]
        c_pos =_