# -*- coding: utf-8 -*-
"""download.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1deUuNQSgBjf_MDRmDLux8aVs9a_FmDmO
"""

import pandas as pd
import streamlit as st
from io import BytesIO

def generate_download_button(result):
    """
    Create a download button for model results as Excel.
    """
    output = BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')

    # 파라미터 저장
    param_df = pd.DataFrame.from_dict(result['params'], orient='index', columns=['value'])
    param_df.to_excel(writer, sheet_name='Parameters')

    # 예측값 저장
    if 'pred' in result:
        if isinstance(result['pred'], pd.Series):
            pred_df = result['pred'].reset_index()
        else:
            pred_df = pd.DataFrame({"Prediction": result['pred']})
        pred_df.to_excel(writer, sheet_name='Prediction', index=False)

    writer.close()
    st.download_button(
        label="📥 결과 다운로드 (Excel)",
        data=output.getvalue(),
        file_name="pk_modeling_result.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )