# -*- coding: utf-8 -*-
"""model_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13o-GcqQAHXI4yAEMiMZVOeMG7ofmrWgy
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from utils.fit import fit_model

def compare_models(data, method, dose=None, R=None, duration=None):
    model_list = [
        "1 컴파트먼트 IV bolus",
        "1 컴파트먼트 PO",
        "2 컴파트먼트 IV bolus",
        "2 컴파트먼트 PO",
        "IV infusion (PI)"
    ]
    results = []
    for model in model_list:
        try:
            result = fit_model(data, model, method, dose=dose, R=R, duration=duration)
            results.append({
                "model": model,
                "AIC": result['aic'],
                "BIC": result['bic']
            })
        except Exception as e:
            results.append({
                "model": model,
                "AIC": float('inf'),
                "BIC": float('inf')
            })
    return pd.DataFrame(results)

def display_comparison(results_df, st):
    st.subheader("📊 모델 비교 결과")
    results_df = results_df.sort_values("AIC")
    st.dataframe(results_df.reset_index(drop=True))

    fig, ax = plt.subplots(figsize=(8, 4))
    sns.barplot(data=results_df, x="AIC", y="model", ax=ax, palette="Blues_r")
    ax.set_title("모델별 AIC 비교")
    st.pyplot(fig)