# -*- coding: utf-8 -*-
"""plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYM1p_d8s6tZJf9daLVFPT-UngBa4--J
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import streamlit as st

def plot_prediction(data, pred):
    st.subheader("📈 모델 예측 vs. 실측 농도")
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(data['time'], data['conc'], 'o', label='Observed')
    ax.plot(data['time'], pred, '-', label='Predicted')
    ax.set_xlabel('Time')
    ax.set_ylabel('Concentration')
    ax.legend()
    ax.grid(True)
    st.pyplot(fig)

def plot_residuals(data, pred):
    residuals = data['conc'] - pred
    st.subheader("📉 잔차 분석")
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.axhline(0, color='gray', linestyle='--')
    ax.plot(data['time'], residuals, 'o-', color='red')
    ax.set_xlabel('Time')
    ax.set_ylabel('Residuals (Observed - Predicted)')
    ax.grid(True)
    st.pyplot(fig)

def plot_terminal_phase(data, terminal_pred, selected_times=None):
    st.subheader("📊 터미널 페이즈 적합")
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(data['time'], data['conc'], 'o', label='Observed')
    ax.plot(data['time'], terminal_pred, '--', label='Terminal Phase Fit')
    if selected_times:
        sel = data['time'].isin(selected_times)
        ax.plot(data['time'][sel], data['conc'][sel], 'ro', label='Selected for Terminal Phase')
    ax.set_yscale('log')
    ax.set_xlabel('Time')
    ax.set_ylabel('Concentration (log scale)')
    ax.legend()
    ax.grid(True)
    st.pyplot(fig)