# -*- coding: utf-8 -*-
"""residuals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5PPdqUCEvfV5_RbW2UEpgDFYPJV8Sx9
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

def calculate_residuals(data, pred):
    residuals = data['conc'] - pred
    return residuals

def residual_summary(residuals):
    return {
        "mean": round(residuals.mean(), 4),
        "std": round(residuals.std(), 4),
        "min": round(residuals.min(), 4),
        "max": round(residuals.max(), 4),
    }

def plot_residual_distribution(residuals):
    st.subheader("📉 잔차 분포")
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.histplot(residuals, kde=True, bins=15, ax=ax, color='orange')
    ax.set_title("Residuals Distribution")
    ax.set_xlabel("Residual")
    ax.set_ylabel("Count")
    st.pyplot(fig)

def plot_residuals_vs_pred(pred, residuals):
    st.subheader("🔍 예측값 vs. 잔차")
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.axhline(0, color='gray', linestyle='--')
    ax.scatter(pred, residuals, color='purple')
    ax.set_xlabel("Predicted Concentration")
    ax.set_ylabel("Residuals")
    ax.grid(True)
    st.pyplot(fig)