# -*- coding: utf-8 -*-
"""iv_infusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtnptkB2u9T81QXoahn5td1p4AgCUbhS
"""

import numpy as np

def one_comp_iv_infusion_conc(t, R, k10, V, duration):
    """
    Calculate plasma concentration for 1-compartment IV infusion.

    Parameters:
        t : array-like
            Time points (hr)
        R : float
            Infusion rate (mg/hr)
        k10 : float
            Elimination rate constant (1/hr)
        V : float
            Volume of distribution (L)
        duration : float
            Infusion duration (hr)

    Returns:
        np.array : Predicted concentrations (mg/L)
    """
    conc = []
    for ti in t:
        if ti <= duration:
            c = (R / (V * k10)) * (1 - np.exp(-k10 * ti))
        else:
            c = (R / (V * k10)) * (1 - np.exp(-k10 * duration)) * np.exp(-k10 * (ti - duration))
        conc.append(c)
    return np.array(conc)